const {test} = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const L = require('./logic.cjs');
const capabilityHash=crypto.createHash('sha256').update('private-owner-capability').digest('hex');
const now=Date.parse('2026-10-10T12:30:00Z');
const config={hostId:'host-1',returnUrl:'https://local.example/setting/subscription?enterpriseLicense=return',productId:'prod_enterprise',prices:{month:'price_month',year:'price_year'},livemode:false};
const body={action:'checkout',hostId:'host-1',orgId:'org-1',userId:'admin-1',issuedAt:now,requestId:'00000000-0000-4000-8000-000000000001',billingInterval:'month',deploymentIds:['host-1','host-2'],returnUrl:config.returnUrl,
contactData:{companyName:'Example / Company',address:'Address, with commas',registerNumber:'123',contactName:'Admin',contactEmail:'admin@example.test',contactPhone:'+123',vatId:''}};
const order=()=>({...L.validateRequest(structuredClone(body),config,now,capabilityHash),customerId:'cus_1',checkoutId:'cs_1'});
const price=()=>({id:'price_month',product:config.productId,active:true,livemode:false,currency:'usd',unit_amount:45900,billing_scheme:'per_unit',recurring:{interval:'month',interval_count:1,usage_type:'licensed'}});
const start=Date.parse('2026-10-10T12:00:00Z')/1000,end=Date.parse('2026-11-10T12:00:00Z')/1000;
const sub=()=>({id:'sub_1',customer:'cus_1',status:'active',livemode:false,items:{has_more:false,data:[{id:'si_1',price:price(),quantity:2,current_period_start:start,current_period_end:end}]},metadata:{lowcoder_license_request:body.requestId,lowcoder_hostId:body.hostId,lowcoder_orgId:body.orgId,lowcoder_userId:body.userId}});
const invoice=()=>({id:'in_1',customer:'cus_1',parent:{subscription_details:{subscription:'sub_1'}},status:'paid',livemode:false,currency:'usd',amount_paid:91800,amount_remaining:0,billing_reason:'subscription_cycle',lines:{has_more:false,data:[{amount:91800,quantity:2,pricing:{price_details:{price:'price_month',product:config.productId}},parent:{subscription_item_details:{proration:false}},period:{start,end}}]}});
const payments=()=>({has_more:false,data:[{invoice:'in_1',status:'paid',currency:'usd',amount_paid:91800,payment:{type:'payment_intent',payment_intent:{status:'succeeded',customer:'cus_1',currency:'usd',amount_received:91800}}}]});

test('prices multiply exactly for all offered quantities',()=>{for(const interval of ['month','year'])for(const count of [1,2,3]){const b=structuredClone(body);b.billingInterval=interval;b.deploymentIds=Array.from({length:count},(_,i)=>`host-${i+1}`);const o=L.validateRequest(b,config,now,capabilityHash);assert.equal(o.unitAmount*o.quantity,({month:[45900,91800,137700],year:[499000,998000,1497000]})[interval][count-1]);}});
test('rejects browser identity/amount spoofing, duplicate deployments and excess instances',()=>{for(const change of [{hostId:'other'}, {issuedAt:now-60000}, {deploymentIds:['host-2']}, {deploymentIds:['host-1','host-1']}, {deploymentIds:['host-1','2','3','4']},{billingInterval:'per-api-calls'},{returnUrl:'http://evil.test'}])assert.throws(()=>L.validateRequest({...body,...change},config,now,capabilityHash));assert.equal(L.validateRequest({...body,unitAmount:1,quantity:500},config,now,capabilityHash).unitAmount,45900);});
test('rejects altered Stripe product, unit amount, mode and billing interval',()=>{for(const change of [{product:'prod_support'},{unit_amount:1},{livemode:true},{transform_quantity:{divide_by:2}},{recurring:{interval:'year',interval_count:1,usage_type:'licensed'}}])assert.throws(()=>L.validatePrice({...price(),...change},order(),config));});
test('Checkout carries immutable owner metadata and quantity; no browser success grants entitlement',()=>{const fields=L.checkoutForm(order(),'cus_1',{integrationIdentifier:'lowcoder_enterprise_kjqmxrav'});assert.equal(fields['line_items[0][quantity]'],2);assert.equal(fields['subscription_data[metadata][lowcoder_userId]'],'admin-1');assert.equal(fields.mode,'subscription');assert.equal(fields.payment_method_types,undefined);const session={id:'cs_1',customer:'cus_1',client_reference_id:body.requestId,metadata:{lowcoder_license_request:body.requestId},subscription:null,payment_status:'paid'};assert.equal(L.checkSession(session,order()),null);});
test('another purchasing admin cannot claim a subscription',()=>{const s=sub();s.metadata.lowcoder_userId='other-admin';assert.throws(()=>L.checkSession({id:'cs_1',customer:'cus_1',client_reference_id:body.requestId,metadata:{lowcoder_license_request:body.requestId},subscription:s},order()));});
test('a fully paid current Enterprise invoice permits exactly its paid period',()=>{assert.deepEqual(L.paidPeriod(invoice(),sub(),order(),config,now,capabilityHash),{invoiceId:'in_1',start,end});});
test('unpaid, expired, future, canceled and paused purchases cannot issue',()=>{assert.equal(L.paidPeriod({...invoice(),status:'open'},sub(),order(),config,now,capabilityHash),null);assert.equal(L.paidPeriod(invoice(),sub(),order(),config,end*1000),null);assert.equal(L.paidPeriod(invoice(),sub(),order(),config,start*1000-1),null);for(const status of ['canceled','paused','past_due','trialing'])assert.equal(L.paidPeriod(invoice(),{...sub(),status},order(),config,now,capabilityHash),null);});
test('wrong customer, product, quantity, partial payment, OOB and prorations fail closed',()=>{for(const change of [{customer:'cus_other'},{amount_paid:45900},{amount_remaining:1},{amount_paid_out_of_band:91800},{paid_out_of_band:true},{billing_reason:'subscription_update'},{livemode:true}])assert.throws(()=>L.paidPeriod({...invoice(),...change},sub(),order(),config,now,capabilityHash));for(const change of [{quantity:1},{amount:1},{pricing:{price_details:{price:'price_support',product:'prod_support'}}},{parent:{subscription_item_details:{proration:true}}}]){const i=invoice();Object.assign(i.lines.data[0],change);assert.throws(()=>L.paidPeriod(i,sub(),order(),config,now,capabilityHash));}});
test('truncated invoice or subscription lines cannot silently grant licenses',()=>{const i=invoice();i.lines.has_more=true;assert.throws(()=>L.paidPeriod(i,sub(),order(),config,now,capabilityHash));const s=sub();s.items.has_more=true;assert.throws(()=>L.paidPeriod(invoice(),s,order(),config,now,capabilityHash));});
test('requires successful Stripe payment intents covering the full invoice',()=>{const period={invoiceId:'in_1',start,end};assert.deepEqual(L.verifyPayments(payments(),period,order()),period);for(const change of [{status:'processing'},{customer:'cus_other'},{amount_received:1}]){const p=payments();Object.assign(p.data[0].payment.payment_intent,change);assert.throws(()=>L.verifyPayments(p,period,order()));}const p=payments();p.has_more=true;assert.throws(()=>L.verifyPayments(p,period,order()));});
test('license dates preserve noon UTC and stop one second before next billing period; API limit always one billion',()=>{const deterministic=key=>crypto.createHash('sha256').update(key).digest('hex').slice(0,32);const plans=L.licensePlan(order(),{invoiceId:'in_1',start,end},deterministic);assert.equal(plans.length,2);assert.notEqual(plans[0].id,plans[1].id);assert.equal(plans[0].body.notBefore,start*1000);assert.equal(plans[0].body.notAfter,(end-1)*1000);assert.equal(plans[0].body.apiCallsLimit,1000000000);assert.equal(plans[0].filename,'Example_Company_host-1_2026-10-10_2026-11-10.lic');assert.deepEqual(plans,L.licensePlan(order(),{invoiceId:'in_1',start,end},deterministic));});
test('invalid server files never become downloadable',()=>{for(const response of [{success:false,license:'abc'},{success:true,license:'<html>error</html>'},{success:true,license:''}])assert.throws(()=>L.generatedFile(response));const file=Buffer.from('signed binary license file').toString('base64');assert.equal(L.generatedFile({success:true,license:file}),file);});

test('self-host identities alone cannot authorize access',()=>{assert.throws(()=>L.validateRequest(body,config,now));const a=order();const b=L.validateRequest(body,config,now,'b'.repeat(64));assert.notEqual(a.capabilityHash,b.capabilityHash);assert.equal(b.hostId,a.hostId);});
test('another HTTPS installation can buy without central host registration',()=>{const o=L.validateRequest({...body,hostId:'another-host',deploymentIds:['another-host'],returnUrl:'https://another.example/setting/subscription?enterpriseLicense=return'},config,now,capabilityHash);assert.equal(o.hostId,'another-host');assert.equal(o.unitAmount,45900);});

test('allows the verified Stripe custom domain but rejects lookalike destinations',()=>{for(const kind of ['checkout','portal']){assert.equal(L.stripeUrl('https://secure.lowcoder.cloud/session',kind),true);for(const value of ['http://secure.lowcoder.cloud/x','https://secure.lowcoder.cloud.evil.test/x','https://secure.lowcoder.cloud@evil.test/x','https://evil.test/'])assert.equal(L.stripeUrl(value,kind),false);}});
test('refunded or disputed charges cannot issue license files',()=>{const intent={status:'succeeded',customer:'cus_1',currency:'usd',amount_received:91800,latest_charge:{paid:true,status:'succeeded',amount_refunded:0,disputed:false}};L.verifyCharge(intent,order());for(const change of [{amount_refunded:1},{disputed:true},{paid:false},{status:'pending'}])assert.throws(()=>L.verifyCharge({...intent,latest_charge:{...intent.latest_charge,...change}},order()));});
