import { UICompType } from "comps/uiCompRegistry";
import { memo } from "react";
import {
  LeftCommon,
  AudioCompIconSmall,
  AutoCompleteCompIconSmall,
  ButtonCompIconSmall,
  CardCompIconSmall,
  CalendarCompIconSmall,
  CarouselCompIconSmall,
  CascaderCompIconSmall,
  ChartCompIconSmall,
  CheckboxCompIconSmall,
  CollapsibleContainerCompIconSmall,
  ColumnLayoutCompIconSmall,
  CommentCompIconSmall,
  ContainerCompIconSmall,
  CustomCompIconSmall,
  DateCompIconSmall,
  DateRangeCompIconSmall,
  DividerCompIconSmall,
  DrawerCompIconSmall,
  DropdownCompIconSmall,
  FileViewerCompIconSmall,
  FloatingButtonCompIconSmall,
  FloatingTextCompIconSmall,
  FormCompIconSmall,
  GridCompIconSmall,
  IconCompIconSmall,
  IconButtonCompIconSmall,
  IFrameCompIconSmall,
  ImageCompIconSmall,
  ImageEditorCompIconSmall,
  InputCompIconSmall,
  JsonEditorCompIconSmall,
  JsonExplorerCompIconSmall,
  JsonFormCompIconSmall,
  LinkCompIconSmall,
  ListViewCompIconSmall,
  LottieAnimationCompIconSmall,
  MentionCompIconSmall,
  MermaidCompIconSmall,
  ModalCompIconSmall,
  ModuleIconSmall,
  MultiSelectCompIconSmall,
  NavComIconSmall,
  NumberInputCompIconSmall,
  PageLayoutCompIconSmall,
  PasswordCompIconSmall,
  ProcessCircleCompIconSmall,
  ProgressCompIconSmall,
  QRCodeCompIconSmall,
  RadioCompIconSmall,
  RangeSliderCompIconSmall,
  RatingCompIconSmall,
  ResponsiveLayoutCompIconSmall,
  SplitLayoutCompIconSmall,
  RichTextEditorCompIconSmall,
  ScannerCompIconSmall,
  SegmentedCompIconSmall,
  SelectCompIconSmall,
  SignatureCompIconSmall,
  SliderCompIconSmall,
  StepCompIconSmall,
  SwitchCompIconSmall,
  TabbedContainerCompIconSmall,
  TableCompIconSmall,
  TextAreaCompIconSmall,
  TextCompIconSmall,
  TimeCompIconSmall,
  TimeLineCompIconSmall,
  TimeRangeCompIconSmall,
  ToggleButtonCompIconSmall,
  TourCompIconSmall,
  TreeDisplayCompIconSmall,
  TreeSelectCompIconSmall,
  UploadCompIconSmall,
  VideoCameraStreamCompIconSmall,
  VideoCompIconSmall,
  VideoMeetingRoomCompIconSmall,
  VideoScreenshareCompIconSmall,
  AvatarCompIconSmall,
  AvatarGroupCompIconSmall,
  ColorPickerCompIconSmall,
  TransferCompIconSmall,
  ShapesCompIconSmall,
  GanttCompIconSmall,
  KanbanCompIconSmall,
  CandlestickChartCompIconSmall,
  FunnelChartCompIconSmall,
  GaugeChartCompIconSmall,
  // GraphChartCompIconSmall,
  HeatmapChartCompIconSmall,
  RadarChartCompIconSmall,
  SankeyChartCompIconSmall,
  SunburstChartCompIconSmall,
  ThemeriverChartCompIconSmall,
  TreeChartCompIconSmall,
  TreemapChartCompIconSmall,
  BPMNEditorCompIconSmall,
  GeoMapChartsCompIconSmall,
  GeoMapLayersCompIconSmall,
  HillchartCompIconSmall,
  TurnstileCaptchaCompIconSmall,
  PivotTableCompIconSmall,
  GraphChartCompIconSmall,
} from "lowcoder-design";

// Memoize icon components to prevent unnecessary re-renders
const MemoizedIcon = memo(({ Icon }: { Icon: React.ComponentType }) => <Icon />);

// Group related icons for better organization
const chartIcons = {
  basicChart: ChartCompIconSmall,
  barChart: ChartCompIconSmall,
  lineChart: ChartCompIconSmall,
  pieChart: ChartCompIconSmall,
  scatterChart: ChartCompIconSmall,
  funnelChart: FunnelChartCompIconSmall,
  gaugeChart: GaugeChartCompIconSmall,
  sankeyChart: SankeyChartCompIconSmall,
  candleStickChart: CandlestickChartCompIconSmall,
  radarChart: RadarChartCompIconSmall,
  heatmapChart: HeatmapChartCompIconSmall,
  graphChart: GraphChartCompIconSmall,
  treeChart: TreeChartCompIconSmall,
  treemapChart: TreemapChartCompIconSmall,
  sunburstChart: SunburstChartCompIconSmall,
  themeriverChart: ThemeriverChartCompIconSmall,
};

const formIcons = {
  input: InputCompIconSmall,
  textArea: TextAreaCompIconSmall,
  numberInput: NumberInputCompIconSmall,
  password: PasswordCompIconSmall,
  select: SelectCompIconSmall,
  multiSelect: MultiSelectCompIconSmall,
  radio: RadioCompIconSmall,
  checkbox: CheckboxCompIconSmall,
  switch: SwitchCompIconSmall,
  slider: SliderCompIconSmall,
  rangeSlider: RangeSliderCompIconSmall,
  date: DateCompIconSmall,
  dateRange: DateRangeCompIconSmall,
  time: TimeCompIconSmall,
  timeRange: TimeRangeCompIconSmall,
};

const layoutIcons = {
  container: ContainerCompIconSmall,
  grid: GridCompIconSmall,
  columnLayout: ColumnLayoutCompIconSmall,
  responsiveLayout: ResponsiveLayoutCompIconSmall,
  splitLayout: SplitLayoutCompIconSmall,
  pageLayout: PageLayoutCompIconSmall,
  tabbedContainer: TabbedContainerCompIconSmall,
  collapsibleContainer: CollapsibleContainerCompIconSmall,
  form: FormCompIconSmall,
};

const mediaIcons = {
  image: ImageCompIconSmall,
  video: VideoCompIconSmall,
  audio: AudioCompIconSmall,
  iframe: IFrameCompIconSmall,
  file: UploadCompIconSmall,
  fileViewer: FileViewerCompIconSmall,
};

// Create a type-safe mapping of component types to their icons
export const CompStateIcon: {
  [key in UICompType]: JSX.Element;
} = {
  // Chart components
  ...Object.entries(chartIcons).reduce((acc, [key, Icon]) => ({
    ...acc,
    [key]: <MemoizedIcon Icon={Icon} />,
  }), {}),

  // Form components
  ...Object.entries(formIcons).reduce((acc, [key, Icon]) => ({
    ...acc,
    [key]: <MemoizedIcon Icon={Icon} />,
  }), {}),

  // Layout components
  ...Object.entries(layoutIcons).reduce((acc, [key, Icon]) => ({
    ...acc,
    [key]: <MemoizedIcon Icon={Icon} />,
  }), {}),

  // Media components
  ...Object.entries(mediaIcons).reduce((acc, [key, Icon]) => ({
    ...acc,
    [key]: <MemoizedIcon Icon={Icon} />,
  }), {}),

  // Individual components
  autocomplete: <MemoizedIcon Icon={AutoCompleteCompIconSmall} />,
  button: <MemoizedIcon Icon={ButtonCompIconSmall} />,
  calendar: <MemoizedIcon Icon={CalendarCompIconSmall} />,
  carousel: <MemoizedIcon Icon={CarouselCompIconSmall} />,
  cascader: <MemoizedIcon Icon={CascaderCompIconSmall} />,
  comment: <MemoizedIcon Icon={CommentCompIconSmall} />,
  controlButton: <MemoizedIcon Icon={IconButtonCompIconSmall} />,
  custom: <MemoizedIcon Icon={CustomCompIconSmall} />,
  divider: <MemoizedIcon Icon={DividerCompIconSmall} />,
  drawer: <MemoizedIcon Icon={DrawerCompIconSmall} />,
  dropdown: <MemoizedIcon Icon={DropdownCompIconSmall} />,
  floatTextContainer: <MemoizedIcon Icon={FloatingTextCompIconSmall} />,
  icon: <MemoizedIcon Icon={IconCompIconSmall} />,
  imageEditor: <MemoizedIcon Icon={ImageEditorCompIconSmall} />,
  jsonEditor: <MemoizedIcon Icon={JsonEditorCompIconSmall} />,
  jsonExplorer: <MemoizedIcon Icon={JsonExplorerCompIconSmall} />,
  jsonLottie: <MemoizedIcon Icon={LottieAnimationCompIconSmall} />,
  jsonSchemaForm: <MemoizedIcon Icon={JsonFormCompIconSmall} />,
  link: <MemoizedIcon Icon={LinkCompIconSmall} />,
  listView: <MemoizedIcon Icon={ListViewCompIconSmall} />,
  meeting: <MemoizedIcon Icon={VideoMeetingRoomCompIconSmall} />,
  mention: <MemoizedIcon Icon={MentionCompIconSmall} />,
  mermaid: <MemoizedIcon Icon={MermaidCompIconSmall} />,
  modal: <MemoizedIcon Icon={ModalCompIconSmall} />,
  module: <MemoizedIcon Icon={ModuleIconSmall} />,
  moduleContainer: <MemoizedIcon Icon={ModuleIconSmall} />,
  navigation: <MemoizedIcon Icon={NavComIconSmall} />,
  npmPlugin: <MemoizedIcon Icon={LeftCommon} />,
  progress: <MemoizedIcon Icon={ProgressCompIconSmall} />,
  progressCircle: <MemoizedIcon Icon={ProcessCircleCompIconSmall} />,
  qrCode: <MemoizedIcon Icon={QRCodeCompIconSmall} />,
  rating: <MemoizedIcon Icon={RatingCompIconSmall} />,
  richTextEditor: <MemoizedIcon Icon={RichTextEditorCompIconSmall} />,
  scanner: <MemoizedIcon Icon={ScannerCompIconSmall} />,
  segmentedControl: <MemoizedIcon Icon={SegmentedCompIconSmall} />,
  sharingcomponent: <MemoizedIcon Icon={VideoScreenshareCompIconSmall} />,
  signature: <MemoizedIcon Icon={SignatureCompIconSmall} />,
  step: <MemoizedIcon Icon={StepCompIconSmall} />,
  table: <MemoizedIcon Icon={TableCompIconSmall} />,
  text: <MemoizedIcon Icon={TextCompIconSmall} />,
  timeline: <MemoizedIcon Icon={TimeLineCompIconSmall} />,
  toggleButton: <MemoizedIcon Icon={ToggleButtonCompIconSmall} />,
  tour: <MemoizedIcon Icon={TourCompIconSmall} />,
  tree: <MemoizedIcon Icon={TreeDisplayCompIconSmall} />,
  treeSelect: <MemoizedIcon Icon={TreeSelectCompIconSmall} />,
  videocomponent: <MemoizedIcon Icon={VideoCameraStreamCompIconSmall} />,
  hillchart: <MemoizedIcon Icon={HillchartCompIconSmall} />,
  ganttChart: <MemoizedIcon Icon={GanttCompIconSmall} />,
  kanban: <MemoizedIcon Icon={KanbanCompIconSmall} />,
  openLayersGeoMap: <MemoizedIcon Icon={GeoMapLayersCompIconSmall} />,
  chartsGeoMap: <MemoizedIcon Icon={GeoMapChartsCompIconSmall} />,
  bpmnEditor: <MemoizedIcon Icon={BPMNEditorCompIconSmall} />,
  turnstileCaptcha: <MemoizedIcon Icon={TurnstileCaptchaCompIconSmall} />,
  pivotTable: <MemoizedIcon Icon={PivotTableCompIconSmall} />,
  avatar: <MemoizedIcon Icon={AvatarCompIconSmall} />,
  avatarGroup: <MemoizedIcon Icon={AvatarGroupCompIconSmall} />,
  colorPicker: <MemoizedIcon Icon={ColorPickerCompIconSmall} />,
  floatingButton: <MemoizedIcon Icon={FloatingButtonCompIconSmall} />,
  transfer: <MemoizedIcon Icon={TransferCompIconSmall} />,
  card: <MemoizedIcon Icon={CardCompIconSmall} />,
  timer: <MemoizedIcon Icon={TimeRangeCompIconSmall} />,
  shape: <MemoizedIcon Icon={ShapesCompIconSmall} />,
  input: <MemoizedIcon Icon={InputCompIconSmall} />,
  textArea: <MemoizedIcon Icon={TextAreaCompIconSmall} />,
  chart: <MemoizedIcon Icon={ChartCompIconSmall} />,
  password: <MemoizedIcon Icon={PasswordCompIconSmall} />,
  select: <MemoizedIcon Icon={SelectCompIconSmall} />,
  multiSelect: <MemoizedIcon Icon={MultiSelectCompIconSmall} />,
  radio: <MemoizedIcon Icon={RadioCompIconSmall} />,
  checkbox: <MemoizedIcon Icon={CheckboxCompIconSmall} />,
  switch: <MemoizedIcon Icon={SwitchCompIconSmall} />,
  slider: <MemoizedIcon Icon={SliderCompIconSmall} />,
  rangeSlider: <MemoizedIcon Icon={RangeSliderCompIconSmall} />,
  date: <MemoizedIcon Icon={DateCompIconSmall} />,
  dateRange: <MemoizedIcon Icon={DateRangeCompIconSmall} />,
  time: <MemoizedIcon Icon={TimeCompIconSmall} />,
  timeRange: <MemoizedIcon Icon={TimeRangeCompIconSmall} />,
  file: <MemoizedIcon Icon={UploadCompIconSmall} />,
  fileViewer: <MemoizedIcon Icon={FileViewerCompIconSmall} />,
  container: <MemoizedIcon Icon={ContainerCompIconSmall} />,
  grid: <MemoizedIcon Icon={GridCompIconSmall} />,
  columnLayout: <MemoizedIcon Icon={ColumnLayoutCompIconSmall} />,
  responsiveLayout: <MemoizedIcon Icon={ResponsiveLayoutCompIconSmall} />,
  splitLayout: <MemoizedIcon Icon={SplitLayoutCompIconSmall} />,
  pageLayout: <MemoizedIcon Icon={PageLayoutCompIconSmall} />,
  tabbedContainer: <MemoizedIcon Icon={TabbedContainerCompIconSmall} />,
  collapsibleContainer: <MemoizedIcon Icon={CollapsibleContainerCompIconSmall} />,
  form: <MemoizedIcon Icon={FormCompIconSmall} />,
  image: <MemoizedIcon Icon={ImageCompIconSmall} />,
  video: <MemoizedIcon Icon={VideoCompIconSmall} />,
  audio: <MemoizedIcon Icon={AudioCompIconSmall} />,
  iframe: <MemoizedIcon Icon={IFrameCompIconSmall} />,
  numberInput: <MemoizedIcon Icon={NumberInputCompIconSmall} />,
  barChart: <MemoizedIcon Icon={ChartCompIconSmall} />,
  lineChart: <MemoizedIcon Icon={ChartCompIconSmall} />,
  pieChart: <MemoizedIcon Icon={ChartCompIconSmall} />,
  scatterChart: <MemoizedIcon Icon={ChartCompIconSmall} />,
  funnelChart: <MemoizedIcon Icon={FunnelChartCompIconSmall} />,
  gaugeChart: <MemoizedIcon Icon={GaugeChartCompIconSmall} />,
  sankeyChart: <MemoizedIcon Icon={SankeyChartCompIconSmall} />,
  candleStickChart: <MemoizedIcon Icon={CandlestickChartCompIconSmall} />,
  radarChart: <MemoizedIcon Icon={RadarChartCompIconSmall} />,
  heatmapChart: <MemoizedIcon Icon={HeatmapChartCompIconSmall} />,
  graphChart: <MemoizedIcon Icon={GraphChartCompIconSmall} />,
  treeChart: <MemoizedIcon Icon={TreeChartCompIconSmall} />,
  treemapChart: <MemoizedIcon Icon={TreemapChartCompIconSmall} />,
  sunburstChart: <MemoizedIcon Icon={SunburstChartCompIconSmall} />,
  themeriverChart: <MemoizedIcon Icon={ThemeriverChartCompIconSmall} />,
  basicChart: <MemoizedIcon Icon={ChartCompIconSmall} />,
} as const;
