import { UICompType } from "comps/uiCompRegistry";
import {
  LeftCommon,
  AudioCompIconSmall,
  AutoCompleteCompIconSmall,
  ButtonCompIconSmall,
  CardCompIconSmall,
  CalendarCompIconSmall,
  CarouselCompIconSmall,
  CascaderCompIconSmall,
  ChartCompIconSmall,
  CheckboxCompIconSmall,
  CollapsibleContainerCompIconSmall,
  ColumnLayoutCompIconSmall,
  CommentCompIconSmall,
  ContainerCompIconSmall,
  CustomCompIconSmall,
  DateCompIconSmall,
  DateRangeCompIconSmall,
  DividerCompIconSmall,
  DrawerCompIconSmall,
  DropdownCompIconSmall,
  FileViewerCompIconSmall,
  FloatingButtonCompIconSmall,
  FloatingTextCompIconSmall,
  FormCompIconSmall,
  GridCompIconSmall,
  IconCompIconSmall,
  IconButtonCompIconSmall,
  IFrameCompIconSmall,
  ImageCompIconSmall,
  ImageEditorCompIconSmall,
  InputCompIconSmall,
  JsonEditorCompIconSmall,
  JsonExplorerCompIconSmall,
  JsonFormCompIconSmall,
  LinkCompIconSmall,
  ListViewCompIconSmall,
  LottieAnimationCompIconSmall,
  MentionCompIconSmall,
  MermaidCompIconSmall,
  ModalCompIconSmall,
  ModuleIconSmall,
  MultiSelectCompIconSmall,
  NavComIconSmall,
  NumberInputCompIconSmall,
  PageLayoutCompIconSmall,
  PasswordCompIconSmall,
  ProcessCircleCompIconSmall,
  ProgressCompIconSmall,
  QRCodeCompIconSmall,
  RadioCompIconSmall,
  RangeSliderCompIconSmall,
  RatingCompIconSmall,
  ResponsiveLayoutCompIconSmall,
  RichTextEditorCompIconSmall,
  ScannerCompIconSmall,
  SegmentedCompIconSmall,
  SelectCompIconSmall,
  SignatureCompIconSmall,
  SliderCompIconSmall,
  StepCompIconSmall,
  SwitchCompIconSmall,
  TabbedContainerCompIconSmall,
  TableCompIconSmall,
  TextAreaCompIconSmall,
  TextCompIconSmall,
  TimeCompIconSmall,
  TimeLineCompIconSmall,
  TimeRangeCompIconSmall,
  ToggleButtonCompIconSmall,
  TourCompIconSmall,
  TreeDisplayCompIconSmall,
  TreeSelectCompIconSmall,
  UploadCompIconSmall,
  VideoCameraStreamCompIconSmall,
  VideoCompIconSmall,
  VideoMeetingRoomCompIconSmall,
  VideoScreenshareCompIconSmall,
  AvatarCompIconSmall,
  AvatarGroupCompIconSmall,
  ColorPickerCompIconSmall,
  TransferCompIconSmall,
  ShapesCompIconSmall,
  GanttCompIconSmall,
  KanbanCompIconSmall,

  CandlestickChartCompIconSmall,
  FunnelChartCompIconSmall,
  GaugeChartCompIconSmall,
  // GraphChartCompIconSmall,
  HeatmapChartCompIconSmall,
  RadarChartCompIconSmall,
  SankeyChartCompIconSmall,
  SunburstChartCompIconSmall,
  ThemeriverChartCompIconSmall,
  TreeChartCompIconSmall,
  TreemapChartCompIconSmall,
  BPMNEditorCompIconSmall,
  GeoMapChartsCompIconSmall,
  GeoMapLayersCompIconSmall,
  HillchartCompIconSmall,
  TurnstileCaptchaCompIconSmall,
  PivotTableCompIconSmall,
  GraphChartCompIconSmall,
} from "lowcoder-design";

export const CompStateIcon: {
  [key in UICompType]: JSX.Element;
} = {
  audio: <AudioCompIconSmall />,
  autocomplete: <AutoCompleteCompIconSmall />,
  button: <ButtonCompIconSmall />,
  calendar: <CalendarCompIconSmall />,
  carousel: <CarouselCompIconSmall />,
  cascader: <CascaderCompIconSmall />,
  chart: <ChartCompIconSmall />,
  checkbox: <CheckboxCompIconSmall />,
  collapsibleContainer: <CollapsibleContainerCompIconSmall />,
  columnLayout: <ColumnLayoutCompIconSmall />,
  comment: <CommentCompIconSmall />,
  container: <ContainerCompIconSmall />,
  controlButton: <IconButtonCompIconSmall />,
  custom: <CustomCompIconSmall />,
  date: <DateCompIconSmall />,
  dateRange: <DateRangeCompIconSmall />,
  divider: <DividerCompIconSmall />,
  drawer: <DrawerCompIconSmall />,
  dropdown: <DropdownCompIconSmall />,
  file: <UploadCompIconSmall />,
  fileViewer: <FileViewerCompIconSmall />,
  floatTextContainer: <FloatingTextCompIconSmall />,
  form: <FormCompIconSmall />,
  grid: <GridCompIconSmall />,
  icon: <IconCompIconSmall />,
  iframe: <IFrameCompIconSmall />,
  image: <ImageCompIconSmall />,
  imageEditor: <ImageEditorCompIconSmall />,
  input: <InputCompIconSmall />,
  jsonEditor: <JsonEditorCompIconSmall />,
  jsonExplorer: <JsonExplorerCompIconSmall />,
  jsonLottie: <LottieAnimationCompIconSmall />,
  jsonSchemaForm: <JsonFormCompIconSmall />,
  link: <LinkCompIconSmall />,
  listView: <ListViewCompIconSmall />,
  meeting: <VideoMeetingRoomCompIconSmall />,
  mention: <MentionCompIconSmall />,
  mermaid: <MermaidCompIconSmall />,
  modal: <ModalCompIconSmall />,
  module: <ModuleIconSmall/>,  
  moduleContainer: <ModuleIconSmall/>,  // Placeholder or specify if there's a dedicated icon
  multiSelect: <MultiSelectCompIconSmall />,
  navigation: <NavComIconSmall />,
  numberInput: <NumberInputCompIconSmall />,
  npmPlugin: <LeftCommon />,  // Placeholder or specify if there's a dedicated icon
  pageLayout: <PageLayoutCompIconSmall />,
  password: <PasswordCompIconSmall />,
  progress: <ProgressCompIconSmall />,
  progressCircle: <ProcessCircleCompIconSmall />,
  qrCode: <QRCodeCompIconSmall />,
  radio: <RadioCompIconSmall />,
  rangeSlider: <RangeSliderCompIconSmall />,
  rating: <RatingCompIconSmall />,
  responsiveLayout: <ResponsiveLayoutCompIconSmall />,
  richTextEditor: <RichTextEditorCompIconSmall />,
  scanner: <ScannerCompIconSmall />,
  segmentedControl: <SegmentedCompIconSmall />,
  select: <SelectCompIconSmall />,
  sharingcomponent: <VideoScreenshareCompIconSmall />,
  signature: <SignatureCompIconSmall />,
  slider: <SliderCompIconSmall />,
  step: <StepCompIconSmall />,
  switch: <SwitchCompIconSmall />,
  tabbedContainer: <TabbedContainerCompIconSmall />,
  table: <TableCompIconSmall />,
  text: <TextCompIconSmall />,
  textArea: <TextAreaCompIconSmall />,
  time: <TimeCompIconSmall />,
  timeRange: <TimeRangeCompIconSmall />,
  timeline: <TimeLineCompIconSmall />,
  toggleButton: <ToggleButtonCompIconSmall />,
  tour: <TourCompIconSmall />, 
  tree: <TreeDisplayCompIconSmall />,
  treeSelect: <TreeSelectCompIconSmall />,
  video: <VideoCompIconSmall />,
  videocomponent: <VideoCameraStreamCompIconSmall />,

  hillchart: <HillchartCompIconSmall/>,  
  ganttChart: <GanttCompIconSmall/>,
  kanban: <KanbanCompIconSmall/>,
  openLayersGeoMap: <GeoMapLayersCompIconSmall/>,  
  chartsGeoMap: <GeoMapChartsCompIconSmall/>,  
  bpmnEditor: <BPMNEditorCompIconSmall/>, 
  turnstileCaptcha: <TurnstileCaptchaCompIconSmall/>,
  pivotTable: <PivotTableCompIconSmall/>,
  funnelChart: <FunnelChartCompIconSmall />,
  gaugeChart: <GaugeChartCompIconSmall />,
  sankeyChart : <SankeyChartCompIconSmall />,
  candleStickChart : <CandlestickChartCompIconSmall />,
  radarChart : <RadarChartCompIconSmall />,
  heatmapChart : <HeatmapChartCompIconSmall />,
  graphChart : <GraphChartCompIconSmall/>,
  treeChart : <TreeChartCompIconSmall />,
  treemapChart : <TreemapChartCompIconSmall />,
  sunburstChart : <SunburstChartCompIconSmall />,
  themeriverChart : <ThemeriverChartCompIconSmall />,
  basicChart : <ChartCompIconSmall />,

  avatar: <AvatarCompIconSmall />,
  avatarGroup: <AvatarGroupCompIconSmall />,
  colorPicker: <ColorPickerCompIconSmall />,
  floatingButton: <FloatingButtonCompIconSmall />,
  transfer: <TransferCompIconSmall />,
  card: <CardCompIconSmall />,
  timer: <TimeRangeCompIconSmall/>,

  shape: <ShapesCompIconSmall />,
};
