export const timeZoneOptions = [
    { label: "(UTC-12:00) International Date Line West", value: "Etc/GMT+12" },
    { label: "(UTC-11:00) Coordinated Universal Time-11", value: "Etc/GMT+11" },
    { label: "(UTC-10:00) Hawaii", value: "Pacific/Honolulu" },
    { label: "(UTC-09:00) Alaska", value: "America/Anchorage" },
    { label: "(UTC-08:00) Baja California", value: "America/Tijuana" },
    { label: "(UTC-07:00) Pacific Daylight Time (US & Canada)", value: "America/Los_Angeles" }, { label: "(UTC-06:00) Central Time (US & Canada)", value: "America/Chicago" },
    { label: "(UTC-05:00) Eastern Time (US & Canada)", value: "America/New_York" },
    { label: "(UTC-04:00) Atlantic Time (Canada)", value: "America/Halifax" },
    { label: "(UTC-03:00) Buenos Aires", value: "America/Argentina/Buenos_Aires" },
    { label: "(UTC-02:00) Coordinated Universal Time-02", value: "Etc/GMT+2" },
    { label: "(UTC-01:00) Cape Verde Is.", value: "Atlantic/Cape_Verde" },
    { label: "Etc/UTC", value: "Etc/UTC" },
    { label: "(UTC+01:00) Amsterdam, Berlin, Rome, Vienna", value: "Europe/Berlin" },
    { label: "(UTC+02:00) Athens, Bucharest", value: "Europe/Bucharest" },
    { label: "(UTC+03:00) Moscow, St. Petersburg", value: "Europe/Moscow" },
    { label: "(UTC+04:00) Abu Dhabi, Muscat", value: "Asia/Dubai" },
    { label: "(UTC+05:00) Islamabad, Karachi", value: "Asia/Karachi" },
    { label: "(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi", value: "Asia/Kolkata" },
    { label: "(UTC+06:00) Dhaka", value: "Asia/Dhaka" },
    { label: "(UTC+07:00) Bangkok, Hanoi, Jakarta", value: "Asia/Bangkok" },
    { label: "(UTC+08:00) Beijing, Chongqing, Hong Kong", value: "Asia/Shanghai" },
    { label: "(UTC+09:00) Tokyo, Seoul", value: "Asia/Tokyo" },
    { label: "(UTC+10:00) Sydney, Melbourne", value: "Australia/Sydney" },
    { label: "User Choice", value: "UserChoice" },
];
