import { trans } from "i18n";

export const timeZoneOptions = [
    { label: trans("timeZone.UTC-12:00"), value: trans("timeZone.UTC-12:00") },
    { label: trans("timeZone.UTC-11:00"), value: trans("timeZone.UTC-11:00") },
    { label: trans("timeZone.UTC-10:00"), value: trans("timeZone.UTC-10:00") },
    { label: trans("timeZone.UTC-09:00"), value: trans("timeZone.UTC-09:00") },
    { label: trans("timeZone.UTC-08:00"), value: trans("timeZone.UTC-08:00") },
    { label: trans("timeZone.UTC-07:00"), value: trans("timeZone.UTC-07:00") },
    { label: trans("timeZone.UTC-06:00"), value: trans("timeZone.UTC-06:00") },
    { label: trans("timeZone.UTC-05:00"), value: trans("timeZone.UTC-05:00") },
    { label: trans("timeZone.UTC-04:00"), value: trans("timeZone.UTC-04:00") },
    { label: trans("timeZone.UTC-03:00"), value: trans("timeZone.UTC-03:00") },
    { label: trans("timeZone.UTC-02:00"), value: trans("timeZone.UTC-02:00") },
    { label: trans("timeZone.UTC-01:00"), value: trans("timeZone.UTC-01:00") },
    { label: trans("timeZone.UTC+00:00"), value: trans("timeZone.UTC+00:00") },
    { label: trans("timeZone.UTC+01:00"), value: trans("timeZone.UTC+01:00") },
    { label: trans("timeZone.UTC+02:00"), value: trans("timeZone.UTC+02:00") },
    { label: trans("timeZone.UTC+03:00"), value: trans("timeZone.UTC+03:00") },
    { label: trans("timeZone.UTC+04:00"), value: trans("timeZone.UTC+04:00") },
    { label: trans("timeZone.UTC+05:00"), value: trans("timeZone.UTC+05:00") },
    { label: trans("timeZone.UTC+05:30"), value: trans("timeZone.UTC+05:30") },
    { label: trans("timeZone.UTC+05:45"), value: trans("timeZone.UTC+05:45") },
    { label: trans("timeZone.UTC+06:00"), value: trans("timeZone.UTC+06:00") },
    { label: trans("timeZone.UTC+06:30"), value: trans("timeZone.UTC+06:30") },
    { label: trans("timeZone.UTC+07:00"), value: trans("timeZone.UTC+07:00") },
    { label: trans("timeZone.UTC+08:00"), value: trans("timeZone.UTC+08:00") },
    { label: trans("timeZone.UTC+09:00"), value: trans("timeZone.UTC+09:00") },
    { label: trans("timeZone.UTC+09:30"), value: trans("timeZone.UTC+09:30") },
    { label: trans("timeZone.UTC+10:00"), value: trans("timeZone.UTC+10:00") },
    { label: trans("timeZone.UTC+11:00"), value: trans("timeZone.UTC+11:00") },
    { label: trans("timeZone.UTC+12:00"), value: trans("timeZone.UTC+12:00") },
    { label: trans("timeZone.UTC+13:00"), value: trans("timeZone.UTC+13:00") },
    { label: trans("timeZone.UserChoice"), value: trans("timeZone.UserChoice") }
];
