package org.lowcoder.api.config;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.security.test.web.reactive.server.SecurityMockServerConfigurers.mockAuthentication;
import static org.springframework.security.test.web.reactive.server.SecurityMockServerConfigurers.springSecurity;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.lowcoder.api.common.InitData;
import org.lowcoder.domain.organization.model.MemberRole;
import org.lowcoder.domain.organization.service.OrgMemberService;
import org.lowcoder.domain.user.model.User;
import org.lowcoder.infra.config.model.ServerConfig;
import org.lowcoder.infra.config.repository.ServerConfigRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.WebFilter;
import reactor.core.publisher.Mono;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.reactive.server.WebTestClient;

/**
 * Pins the authorisation of the server-configuration write through the production request stack (real
 * {@code SecurityConfig}, filters, codecs and {@code ConfigController}) on a MongoDB container.
 *
 * <p>Pinned under D-6, plan §9 row "any signed-in user can write any server configuration key (POST /api/configs/{key},
 * no role check)": {@code ConfigController.updateServerConfig} (ConfigController:44-48, ConfigEndpoints:44) upserts the key
 * for every authenticated caller; {@code SecurityConfig} permits only the GET of that path without a login and lets every
 * other request through once authenticated (anyExchange().authenticated()); there is no role, admin or super-admin check.
 * The caller here is {@code user02}, a plain MEMBER of {@code org01} in the seed data. A fix (an admin or super-admin
 * check) makes the pin fail on purpose.
 *
 * <p>What a user can change: the keys read through {@code AutoReloadConfigFactory} (a 3 s reload cache over every
 * {@code server_config} row, key = {@code <group>.<key>}): see {@link #CONFIG_KEYS_READ_BY_THE_SERVER}.
 *
 * <p>Isolation: its own profile ({@code serverConfigWriteAuth}, own context and database); only a key generated by this
 * test is written (never {@code isRateLimited}, {@code deployment.*} or any other real key) and it is deleted after each test.
 */
@SpringBootTest
@Import(ServerConfigWriteAuthorisationTest.NettyStatusFallback.class)
@ActiveProfiles("serverConfigWriteAuth")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class ServerConfigWriteAuthorisationTest {

    /**
     * Keys the server reads from {@code server_config} (AutoReloadConfigFactory:23-30, through
     * ConfigCenterImpl's {@code <group>.<key>} naming, ConfigCenterImpl:89-94) or by name, with the reading code.
     */
    static final List<String> CONFIG_KEYS_READ_BY_THE_SERVER = List.of(
            "asset.logoMaxSizeInKb (OrganizationServiceImpl:74)",
            "asset.thumbNailPhotoDimension (AssetServiceImpl:43)",
            "asset.avatarMaxSizeInKb (UserServiceImpl:83)",
            "deployment.js-executor.host (CommonConfigHelper:19; the base URL of every JS executor call: NodeServerHelper:25, DatasourcePluginClient:101)",
            "deployment.id (ConfigController:30, AppEventListener:33)",
            "threshold.urlRateLimiter (ThrottlingFilter:47)",
            "threshold.maxRequestSize, threshold.maxResponseSize (QueryExecuteHttpBodySizeFilter:61,63)",
            "threshold.maxOrgPerUser, userOrgCountWhiteList, maxOrgMemberCount, orgMemberCountWhiteList, maxOrgGroupCount, maxOrgAppCount, orgAppCountWhiteList, maxDeveloperCount (BizThresholdChecker:50-57)",
            "isRateLimited (APIDelayFilter:29), and any key a plugin reads with LowcoderServices.getConfig (SharedPluginServices:57-60)");

    /**
     * The mock response of {@code WebTestClient} reports a status never set as null, the Reactor Netty response of the
     * server reports 200 ({@code ReactorServerHttpResponse.getStatusCode}); {@code ApiEventFilter} reads the status after
     * the chain. This filter gives the mock response the Netty behaviour, so the stack behaves as in production.
     */
    @TestConfiguration
    static class NettyStatusFallback {
        @Bean
        WebFilter nettyStatusFallbackFilter() {
            return (exchange, chain) -> {
                exchange.getResponse().beforeCommit(() -> {
                    if (exchange.getResponse().getStatusCode() == null) {
                        exchange.getResponse().setStatusCode(HttpStatus.OK);
                    }
                    return Mono.empty();
                });
                return chain.filter(exchange);
            };
        }
    }

    private static final String MEMBER_USER_ID = "user02";
    private static final String ORG_ID = "org01";
    private static final Duration WAIT = Duration.ofSeconds(30);

    @Autowired
    private ApplicationContext context;
    @Autowired
    private ServerConfigRepository serverConfigRepository;
    @Autowired
    private OrgMemberService orgMemberService;
    @Autowired
    private InitData initData;

    private WebTestClient web;
    private final List<String> writtenKeys = new ArrayList<>();

    @BeforeAll
    void beforeAll() {
        initData.init();
    }

    @BeforeEach
    void setUp() {
        web = WebTestClient.bindToApplicationContext(context).apply(springSecurity()).configureClient()
                .responseTimeout(WAIT).build();
    }

    @AfterEach
    void cleanUp() {
        for (String key : writtenKeys) {
            ServerConfig stored = serverConfigRepository.findByKey(key).block(WAIT);
            if (stored != null) {
                serverConfigRepository.deleteById(stored.getId()).block(WAIT);
            }
        }
        System.out.println("[ServerConfigWriteAuthorisationTest] removed own keys " + writtenKeys);
        writtenKeys.clear();
    }

    private String ownKey() {
        String key = "l2-9-test-key-" + UUID.randomUUID();
        writtenKeys.add(key);
        return key;
    }

    private static UsernamePasswordAuthenticationToken signedIn(String userId) {
        User user = new User();
        user.setId(userId);
        user.setName(userId);
        return new UsernamePasswordAuthenticationToken(user, "n/a", Collections.emptyList());
    }

    /**
     * Pins plan §9 row "any signed-in user can write any server configuration key": a plain org MEMBER writes a key
     * with POST /api/configs/{key}; the value is stored and read back through GET.
     */
    @Test
    void aSignedInNonAdminUser_canWriteAnyServerConfigKey_pinsTheSection9Row() {
        assertThat(orgMemberService.getOrgMember(ORG_ID, MEMBER_USER_ID).block(WAIT).getRole())
                .as("the caller is a plain member of the org, not an admin").isEqualTo(MemberRole.MEMBER);
        String key = ownKey();
        String value = "written-by-a-member-" + UUID.randomUUID();

        web.mutateWith(mockAuthentication(signedIn(MEMBER_USER_ID))).post().uri("/api/configs/" + key)
                .bodyValue(new ConfigEndpoints.UpdateConfigRequest(value)).exchange()
                .expectStatus().isOk()
                .expectBody().jsonPath("$.data.key").isEqualTo(key).jsonPath("$.data.value").isEqualTo(value);

        assertThat(serverConfigRepository.findByKey(key).block(WAIT).getValue()).isEqualTo(value);
        web.mutateWith(mockAuthentication(signedIn(MEMBER_USER_ID))).get().uri("/api/configs/" + key).exchange()
                .expectStatus().isOk()
                .expectBody().jsonPath("$.data.value").isEqualTo(value);
        System.out.println("[ServerConfigWriteAuthorisationTest] member " + MEMBER_USER_ID + " wrote and read back " + key);
    }

    /** A second write replaces the value (an upsert), again by the member. */
    @Test
    void aSignedInNonAdminUser_canOverwriteTheValue_pinsTheSection9Row() {
        String key = ownKey();
        for (String value : List.of("first", "second")) {
            web.mutateWith(mockAuthentication(signedIn(MEMBER_USER_ID))).post().uri("/api/configs/" + key)
                    .bodyValue(new ConfigEndpoints.UpdateConfigRequest(value)).exchange().expectStatus().isOk();
        }

        assertThat(serverConfigRepository.findByKey(key).block(WAIT).getValue()).isEqualTo("second");
        assertThat(serverConfigRepository.findAll().filter(config -> key.equals(config.getKey())).count().block(WAIT)).isEqualTo(1L);
    }

    /** The only barrier is the login: without authentication the write is refused and nothing is stored. */
    @Test
    void withoutALogin_theWriteIsRefused_andNothingIsStored() {
        String key = ownKey();

        web.post().uri("/api/configs/" + key).bodyValue(new ConfigEndpoints.UpdateConfigRequest("anonymous")).exchange()
                .expectStatus().is4xxClientError();

        assertThat(serverConfigRepository.findByKey(key).block(WAIT)).isNull();
    }
}
