services:

  ##
  ## Start services required for Lowcoder (MongoDB and Redis)
  ##
  mongodb:
    image: "mongo:7.0"
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: lowcoder
      MONGO_INITDB_ROOT_USERNAME: lowcoder
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - ./lowcoder-stacks/data/mongodb:/data/db
    restart: unless-stopped
    healthcheck: # https://github.com/rodrigobdz/docker-compose-healthchecks?tab=readme-ov-file#mongo
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    healthcheck: # https://stackoverflow.com/a/71504657
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 10

  hocuspocus:
    image: lowcoderorg/lowcoder-hocuspocus:latest
    container_name: hocuspocus
    restart: unless-stopped
    environment:
      HOCUSPOCUS_SECRET: "s3cr3t! - CHANGE THIS!"

  agora-token-service:
    image: agoracn/token:0.1.2023053011
    container_name: agora-token-service
    restart: unless-stopped
    environment:
      APP_ID: lowcoder
      APP_CERTIFICATE: "your agora token certificate"


  ##
  ## Start Lowcoder backend services (api-service and node-service)
  ##
  lowcoder-api-service:
    image: lowcoderorg/lowcoder-ce-api-service:latest
    container_name: lowcoder-api-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "8080:8080"
    env_file:
      - path: ./default.env
        required: true
      - path: ./default-multi.env
        required: true
      - path: ./override.env
        required: false
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    volumes:
      - ./lowcoder-stacks:/lowcoder-stacks
      - ./lowcoder-stacks/assets:/lowcoder/assets
    healthcheck: #https://stackoverflow.com/questions/71101967/how-should-i-use-grep-in-docker-compose-healthcheck
      test: curl -sS http://lowcoder-api-service:8080  | grep -c "Lowcoder API is up and runnig" > /dev/null
      interval: 3s
      timeout: 5s
      retries: 10


  lowcoder-node-service:
    image: lowcoderorg/lowcoder-ce-node-service:latest
    container_name: lowcoder-node-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "6060:6060"
    env_file:
      - path: ./default.env
        required: true
      - path: ./default-multi.env
        required: true
      - path: ./override.env
        required: false
    restart: unless-stopped
    depends_on:
      lowcoder-api-service:
        condition: service_healthy
        restart: true
    healthcheck: #https://stackoverflow.com/questions/71101967/how-should-i-use-grep-in-docker-compose-healthcheck
      test: curl -sS http://lowcoder-node-service:6060  | grep -c "Lowcoder Node Service is up and running" > /dev/null
      interval: 3s
      timeout: 5s
      retries: 15
      start_period: 40s

  lowcoder-proxy-service:
    build:
      context: ../../server/proxy-service
      dockerfile: Dockerfile
    container_name: lowcoder-proxy-service
    ports:
      - "6070:6070"
    environment:
      PROXY_SERVICE_PORT: "6070"
    env_file:
      - path: ./default.env
        required: true
      - path: ./default-multi.env
        required: true
      - path: ./override.env
        required: false
    restart: unless-stopped
    depends_on:
      lowcoder-api-service:
        condition: service_healthy
        restart: true
    healthcheck:
      test: curl -sS http://lowcoder-proxy-service:6070 | grep -c "Lowcoder Proxy Service is up and running" > /dev/null
      interval: 3s
      timeout: 5s
      retries: 10

  ##
  ## Start Lowcoder web frontend
  ##
  lowcoder-frontend:
    image: lowcoderorg/lowcoder-ce-frontend:latest
    container_name: lowcoder-frontend
    ports:
      - "3000:3000"
    env_file:
      - path: ./default.env
        required: true
      - path: ./default-multi.env
        required: true
      - path: ./override.env
        required: false
    restart: unless-stopped
    depends_on:
      lowcoder-node-service:
        condition: service_healthy
        restart: true
      lowcoder-api-service:
        condition: service_healthy
        restart: true
      lowcoder-proxy-service:
        condition: service_healthy
        restart: true
    volumes:
      - ./lowcoder-stacks/assets:/lowcoder/assets
      - ./lowcoder-stacks/ssl:/lowcoder-stacks/ssl
    healthcheck:
      test: curl --fail http://lowcoder-frontend:3000 || exit 1
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 10s

