
export enum SubscriptionProductsEnum {
  SUPPORT = "QW8L3WPMiNjQjI",
  MEDIAPACKAGE = 'QW8MpIBHxieKXd',
  AZUREAPIS = 'premium',
  GOOGLEAPIS = 'enterprise',
  AWSAPIS = 'enterprise-global',
  PRIVATECLOUD = 'private-cloud',
  MATRIXCLOUD = 'matrix-cloud',
  AGORATOKENSERVER = 'agora-tokenserver',
  SIGNALSERVER = 'signal-server',
  DATABASE = 'database',
  STORAGE = 'storage',
  IOSAPP = 'ios-app',
  ANDROIDAPP = 'android-app',
  AUDITLOG = 'audit-log',
  APPLOG = 'app-log',
  ENVIRONMENTS = 'environments',
  GITREPOS = 'git-repos',
}

export const SubscriptionProducts = [
  {
    pricingType: "Monthly, per User",
    activeSubscription: false,
    accessLink: "1PhH38DDlQgecLSfSukEgIeV",
    product: SubscriptionProductsEnum.SUPPORT,
    subscriptionId: "",
    checkoutLink: "",
    checkoutLinkDataLoaded: false,
    type: "org",
    quantity_entity: "orgUser",
  },
  {
    pricingType: "Monthly, per User",
    activeSubscription: false,
    accessLink: "1Pf65wDDlQgecLSf6OFlbsD5",
    product: SubscriptionProductsEnum.MEDIAPACKAGE,
    checkoutLink: "",
    checkoutLinkDataLoaded: false,
    subscriptionId: "",
    type: "user",
    quantity_entity: "singleItem",
  },
  {
    pricingType: "Monthly, per User",
    activeSubscription: false,
    accessLink: "1PttHIDDlQgecLSf0XP27tXt",
    product: "QlQ7cdOh8Lv4dy",
    subscriptionId: "",
    checkoutLink: "",
    checkoutLinkDataLoaded: false,
    type: "org",
    quantity_entity: "singleItem",
  },
]