package org.lowcoder.domain.organization.service;

import com.github.f4b6a3.uuid.UuidCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.lowcoder.domain.asset.model.Asset;
import org.lowcoder.domain.asset.service.AssetRepository;
import org.lowcoder.domain.asset.service.AssetService;
import org.lowcoder.domain.group.service.GroupService;
import org.lowcoder.domain.organization.event.OrgDeletedEvent;
import org.lowcoder.domain.organization.model.*;
import org.lowcoder.domain.organization.model.Organization.OrganizationCommonSettings;
import org.lowcoder.domain.organization.repository.OrganizationRepository;
import org.lowcoder.domain.user.model.User;
import org.lowcoder.domain.user.repository.UserRepository;
import org.lowcoder.domain.util.SlugUtils;
import org.lowcoder.infra.annotation.PossibleEmptyMono;
import org.lowcoder.infra.birelation.BiRelationService;
import org.lowcoder.infra.birelation.BiRelation;
import org.lowcoder.infra.mongo.MongoUpsertHelper;
import org.lowcoder.sdk.config.CommonConfig;
import org.lowcoder.sdk.config.dynamic.Conf;
import org.lowcoder.sdk.config.dynamic.ConfigCenter;
import org.lowcoder.sdk.constants.FieldName;
import org.lowcoder.sdk.constants.WorkspaceMode;
import org.lowcoder.sdk.exception.BizError;
import org.lowcoder.sdk.exception.BizException;
import org.lowcoder.sdk.util.UriUtils;
import org.springframework.context.ApplicationContext;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.data.mongodb.core.query.Update;
import org.springframework.http.codec.multipart.Part;
import org.springframework.stereotype.Service;
import org.springframework.data.domain.Pageable;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.Collection;
import java.util.Locale;

import static org.lowcoder.domain.organization.model.OrganizationState.ACTIVE;
import static org.lowcoder.domain.organization.model.OrganizationState.DELETED;
import static org.lowcoder.domain.util.QueryDslUtils.fieldName;
import static org.lowcoder.sdk.exception.BizError.UNABLE_TO_FIND_VALID_ORG;
import static org.lowcoder.infra.birelation.BiRelationBizType.ORG_MEMBER;
import static org.lowcoder.sdk.util.ExceptionUtils.deferredError;
import static org.lowcoder.sdk.util.ExceptionUtils.ofError;
import static org.lowcoder.sdk.util.LocaleUtils.getLocale;
import static org.lowcoder.sdk.util.LocaleUtils.getMessage;

@Slf4j
@RequiredArgsConstructor
@Service
public class OrganizationServiceImpl implements OrganizationService {

    /** The Organization property that holds the logo's asset id. */
    private static final String LOGO_ASSET_ID = "logoAssetId";

    private final UserRepository userRepository;
    private Conf<Integer> logoMaxSizeInKb;
    private final AssetRepository assetRepository;
    private final AssetService assetService;
    private final OrgMemberService orgMemberService;
    private final MongoUpsertHelper mongoUpsertHelper;
    private final OrganizationRepository repository;
    private final GroupService groupService;
    private final ApplicationContext applicationContext;
    private final CommonConfig commonConfig;
    private final ConfigCenter configCenter;
    private final BiRelationService biRelationService;

    @PostConstruct
    private void init()
    {
        logoMaxSizeInKb = configCenter.asset().ofInteger("logoMaxSizeInKb", 300);
    }

    @Override
    public Mono<Organization> createDefault(User user, boolean isSuperAdmin) {
        return Mono.deferContextual(contextView -> {
            Locale locale = getLocale(contextView);
            String userOrgSuffix = getMessage(locale, "USER_ORG_SUFFIX");

            Organization organization = new Organization();
            organization.setGid(UuidCreator.getTimeOrderedEpoch().toString());
            organization.setName(user.getName() + userOrgSuffix);
            organization.setIsAutoGeneratedOrganization(true);
            // saas mode
            if (commonConfig.getWorkspace().getMode() == WorkspaceMode.SAAS) {
                return create(organization, user.getId(), isSuperAdmin);
            }
            // enterprise mode
            return joinOrganizationInEnterpriseMode(user.getId())
                    .flatMap(join -> {
                        if (Boolean.TRUE.equals(join)) {
                            return Mono.empty();
                        }
                        return create(organization, user.getId(), isSuperAdmin);
                    });
        });
    }

    private Mono<Boolean> joinOrganizationInEnterpriseMode(String userId) {
        return getOrganizationInEnterpriseMode()
                .flatMap(organization -> orgMemberService.addMember(organization.getId(), userId, MemberRole.MEMBER))
                .defaultIfEmpty(false);
    }

    @Override
    @PossibleEmptyMono
    public Mono<Organization> getOrganizationInEnterpriseMode() {
        if (commonConfig.getWorkspace().getMode() == WorkspaceMode.SAAS) {
            return Mono.empty();
        }
        return getByEnterpriseOrgId()
                .switchIfEmpty(repository.findFirstByStateMatches(ACTIVE));
    }

    @Nonnull
    private Mono<Organization> getByEnterpriseOrgId() {
        String enterpriseOrgId = commonConfig.getWorkspace().getEnterpriseOrgId();
        if (StringUtils.isBlank(enterpriseOrgId)) {
            return Mono.empty();
        }
        return repository.findById(enterpriseOrgId)
                .delayUntil(org -> {
                            if (org.getState() == DELETED) {
                                return ofError(BizError.ORG_DELETED_FOR_ENTERPRISE_MODE, "ORG_DELETED_FOR_ENTERPRISE_MODE");
                            }
                            return Mono.empty();
                        }
                );
    }

    @Override
    public Mono<Organization> create(Organization organization, String creatorId, boolean isSuperAdmin) {

        return Mono.defer(() -> {
                    if (organization == null || StringUtils.isNotBlank(organization.getId())) {
                        return Mono.error(new BizException(BizError.INVALID_PARAMETER, "INVALID_PARAMETER", FieldName.ORGANIZATION));
                    }
                    organization.setCommonSettings(new OrganizationCommonSettings());
                    organization.getCommonSettings().put(OrganizationCommonSettings.PASSWORD_RESET_EMAIL_TEMPLATE,
                            PASSWORD_RESET_EMAIL_TEMPLATE_DEFAULT);
                    organization.setState(ACTIVE);
                    return Mono.just(organization);
                })
                .flatMap(repository::save)
                .flatMap(newOrg -> onOrgCreated(creatorId, newOrg, isSuperAdmin))
                .log();
    }

    private Mono<Organization> onOrgCreated(String userId, Organization newOrg, boolean isSuperAdmin) {
        return groupService.createAllUserGroup(newOrg.getId())
                .then(groupService.createDevGroup(newOrg.getId()))
                .then(setOrgAdmin(userId, newOrg, isSuperAdmin))
                .then(userRepository.findBySuperAdminIsTrue().flatMap(superAdminUser -> {
                    if(!userId.equals(superAdminUser.getId())) {
                        return setOrgSuperAdmin(superAdminUser.getId(), newOrg);
                    }
                    return Mono.empty();
                }).then())
                .thenReturn(newOrg);
    }

    private Mono<Boolean> setOrgAdmin(String userId, Organization newOrg, boolean isSuperAdmin) {
        return orgMemberService.addMember(newOrg.getId(), userId, isSuperAdmin ? MemberRole.SUPER_ADMIN : MemberRole.ADMIN);
    }

    private Mono<Boolean> setOrgSuperAdmin(String userId, Organization newOrg) {
        return orgMemberService.addMember(newOrg.getId(), userId, MemberRole.SUPER_ADMIN);
    }

    /**
     * The active organization named by an object id, a gid or a slug. A key with a hyphen is looked up as a gid and then
     * as a slug (BF-133: SlugUtils accepts a hyphen in a slug, and such a slug was never looked up), any other key as a
     * slug and then as an object id. The same order holds for {@link #getByIdWithDeleted} and {@link #getOrgCommonSettings};
     * {@link #getByIds} takes the kind of its first key for the whole list, as before.
     */
    @Override
    public Mono<Organization> getById(String id) {
        if(FieldName.isGID(id))
            return repository.findByGidAndState(id, ACTIVE)
                    .switchIfEmpty(repository.findBySlugAndState(id, ACTIVE))
                    .switchIfEmpty(deferredError(UNABLE_TO_FIND_VALID_ORG, "INVALID_ORG_ID"));
        return repository.findBySlugAndState(id, ACTIVE).switchIfEmpty(repository.findByIdAndState(id, ACTIVE))
                .switchIfEmpty(deferredError(UNABLE_TO_FIND_VALID_ORG, "INVALID_ORG_ID"));
    }

    @Override
    public Mono<Organization> getByIdWithDeleted(String id) {
        if(FieldName.isGID(id))
            return repository.findByGid(id).next()
                    .switchIfEmpty(repository.findBySlug(id).next())
                    .switchIfEmpty(deferredError(UNABLE_TO_FIND_VALID_ORG, "INVALID_ORG_ID"));
        return repository.findBySlug(id).next().switchIfEmpty(repository.findById(id))
                .switchIfEmpty(deferredError(UNABLE_TO_FIND_VALID_ORG, "INVALID_ORG_ID"));
    }

    @Override
    public Mono<OrganizationCommonSettings> getOrgCommonSettings(String orgId) {
        if(FieldName.isGID(orgId))
            return repository.findByGidAndState(orgId, ACTIVE)
                    .switchIfEmpty(repository.findBySlugAndState(orgId, ACTIVE))
                    .switchIfEmpty(deferredError(UNABLE_TO_FIND_VALID_ORG, "INVALID_ORG_ID"))
                    .map(Organization::getCommonSettings);
        return repository.findBySlugAndState(orgId, ACTIVE).switchIfEmpty(repository.findByIdAndState(orgId, ACTIVE))
                .switchIfEmpty(deferredError(UNABLE_TO_FIND_VALID_ORG, "INVALID_ORG_ID"))
                .map(Organization::getCommonSettings);
    }

    @Override
    public Flux<Organization> getByIds(Collection<String> ids) {
        if(!ids.isEmpty() && FieldName.isGID(ids.stream().findFirst().get()))
            return repository.findByGidInAndState(ids, ACTIVE).switchIfEmpty(repository.findBySlugInAndState(ids, ACTIVE));
        return repository.findBySlugInAndState(ids, ACTIVE).switchIfEmpty(repository.findByIdInAndState(ids, ACTIVE));
    }

    @Override
    public Flux<Organization> getAllActive() {
        return repository.findByState(ACTIVE);
    }

    /**
     * Stores the uploaded logo, points the organization at it, and then removes the logo it pointed at before (BF-063: the
     * previous id was read from a new, empty Organization, so the old logo was never removed). The organization is looked up
     * first (by id, gid or slug, {@link #getById}) and updated by its id.
     * <p>
     * Limits: two uploads for the same organization at the same time both read the same previous logo, so the asset of
     * the upload that is overwritten first is left stored.
     */
    @Override
    public Mono<Boolean> uploadLogo(String organizationId, Part filePart) {
        return getById(organizationId)
                .flatMap(organization -> assetService.upload(filePart, logoMaxSizeInKb.get(), false)
                        .flatMap(uploadedAsset -> {
                            Organization update = new Organization();
                            update.setLogoAssetId(uploadedAsset.getId());
                            return mongoUpsertHelper.updateById(update, organization.getId());
                        })
                        .flatMap(updateResult -> {
                            String prevAssetId = organization.getLogoAssetId();
                            if (StringUtils.isEmpty(prevAssetId)) {
                                return Mono.just(updateResult);
                            }
                            return assetService.remove(prevAssetId).thenReturn(updateResult);
                        }));
    }

    /**
     * Removes the organization's logo: its reference is unset and then its asset deleted (BF-064: the reference was left,
     * because a null field is not written, and the update used the raw argument instead of the organization found by gid
     * or slug). Clearing the reference first means a failed asset delete leaves an unused asset, not a broken logo.
     * <p>
     * Limits: a reference to an asset that no longer exists fails with {@code ASSET_NOT_FOUND} and is kept; uploading a
     * new logo replaces it.
     */
    @Override
    public Mono<Boolean> deleteLogo(String organizationId) {
        return getById(organizationId)
                .flatMap(organization -> {
                    final String prevAssetId = organization.getLogoAssetId();
                    if (StringUtils.isBlank(prevAssetId)) {
                        return Mono.error(new BizException(BizError.NO_RESOURCE_FOUND, "ASSET_NOT_FOUND", ""));
                    }
                    return assetRepository.findById(prevAssetId)
                            .switchIfEmpty(Mono.error(new BizException(BizError.NO_RESOURCE_FOUND, "ASSET_NOT_FOUND", prevAssetId)))
                            .flatMap(asset -> mongoUpsertHelper.updateAndUnset(new Organization(),
                                            new Query(Criteria.where(FieldName.ID).is(organization.getId())), LOGO_ASSET_ID)
                                    .flatMap(updateResult -> assetRepository.delete(asset).thenReturn(updateResult)));
                });
    }

    @Override
    public Mono<Boolean> update(String orgId, Organization updateOrg) {
        return mongoUpsertHelper.updateById(updateOrg, orgId);
    }

    /**
     * Marks the organization deleted and publishes one {@link OrgDeletedEvent}, whose listener removes its members, groups,
     * applications and datasources. Only an organization that is not deleted yet is matched (BF-135: the update matched a
     * deleted one too and, since its auditing fields moved, reported a change, so a second delete answered true and
     * published the event again); a second delete answers false and publishes nothing. The key is an object id or a gid,
     * as for {@code MongoUpsertHelper.updateById}. Limit: the event carries the key as given, so a delete by gid sends the
     * gid to the cleanup listener, which removes by object id (the REST caller passes the object id).
     */
    @Override
    public Mono<Boolean> delete(String orgId) {
        Organization organization = new Organization();
        organization.setState(OrganizationState.DELETED);
        Query notYetDeleted = new Query(Criteria.where(FieldName.guessFieldNameFromId(orgId)).is(orgId)
                .and(fieldName(QOrganization.organization.state)).ne(OrganizationState.DELETED));
        return mongoUpsertHelper.update(organization, notYetDeleted)
                .delayUntil(success -> {
                    if (Boolean.TRUE.equals(success)) {
                        return sendOrgDeletedEvent(orgId);
                    }
                    return Mono.empty();
                });
    }

    private Mono<Void> sendOrgDeletedEvent(String orgId) {
        OrgDeletedEvent event = new OrgDeletedEvent();
        event.setOrgId(orgId);
        applicationContext.publishEvent(event);
        return Mono.empty();
    }

    @Override
    public Mono<Organization> getBySourceAndTpCompanyId(String source, String companyId) {
        return repository.findBySourceAndThirdPartyCompanyIdAndState(source, companyId, ACTIVE);
    }

    @Override
    public Mono<Organization> getByDomain() {
        return UriUtils.getRefererDomainFromContext()
                .flatMap(domain -> repository.findByOrganizationDomain_DomainAndState(domain, ACTIVE));
    }

    @Override
    public Mono<Boolean> updateCommonSettings(String orgId, String key, Object value) {
        long updateTime = System.currentTimeMillis();
        Update update = Update.update(fieldName(QOrganization.organization.commonSettings) + "." + key, value)
                .set(fieldName(QOrganization.organization.commonSettings) + "." + buildCommonSettingsUpdateTimeKey(key), updateTime);
        return mongoUpsertHelper.upsert(update, FieldName.ID, orgId, Organization.class);
    }

    private String buildCommonSettingsUpdateTimeKey(String key) {
        return OrganizationCommonSettings.updateTimeKey(key);
    }

    @Override
    public Mono<Organization> updateSlug(String organizationId, String newSlug) {
        return repository.existsBySlug(newSlug).flatMap(exists -> {
            if (!SlugUtils.validate(newSlug)) {
                return Mono.error(new BizException(BizError.SLUG_INVALID, "SLUG_INVALID"));
            }
            if (exists) {
                return Mono.error(new BizException(BizError.SLUG_DUPLICATE_ENTRY, "SLUG_DUPLICATE_ENTRY"));
            }
            return repository.findById(organizationId)
                    .flatMap(organization -> {
                        organization.setSlug(newSlug);
                        return repository.save(organization);
                    });
        });
    }

    @Override
    public Flux<Organization> findUserOrgs(String userId, String orgName, Pageable pageable) {
        return biRelationService.getByTargetId(ORG_MEMBER, userId)
                .map(BiRelation::getSourceId)
                .collectList()
                .flatMapMany(orgIds -> {
                    if (orgIds.isEmpty()) {
                        return Flux.empty();
                    }
                    return repository.findByIdInAndNameContainingIgnoreCaseAndState(orgIds, orgName, ACTIVE, pageable);
                });
    }

    @Override
    public Mono<Long> countUserOrgs(String userId, String orgName) {
        String filter = orgName == null ? "" : orgName;
        return biRelationService.getByTargetId(ORG_MEMBER, userId)
                .map(BiRelation::getSourceId)
                .collectList()
                .flatMap(orgIds -> {
                    if (orgIds.isEmpty()) {
                        return Mono.just(0L);
                    }
                    return repository.countByIdInAndNameContainingIgnoreCaseAndState(orgIds, filter, ACTIVE);
                });
    }
}
