package org.lowcoder.plugin.mongo.utils;

import org.bson.Document;
import org.bson.types.Decimal128;
import org.bson.types.ObjectId;
import org.junit.jupiter.api.Test;
import org.lowcoder.sdk.models.DatasourceStructure;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit MG-5 (task L5-8c), collection structure: {@code MongoQueryUtils.generateTemplatesAndStructureForACollection} turns a
 * sample document into the column list the schema browser shows: one column per field with a type label, sorted by name;
 * only an ObjectId is marked auto-generated. Also {@code urlEncode}.
 *
 * <p>Limits: the sample is the caller's; how {@code getStructure} picks it from a collection is MG-6.
 */
public class MongoQueryUtilsStructureTest {

    static final String TAG = "[MongoQueryUtilsStructureTest] ";

    private static List<DatasourceStructure.Column> columns(Document sample) {
        ArrayList<DatasourceStructure.Column> columns = new ArrayList<>();
        MongoQueryUtils.generateTemplatesAndStructureForACollection(sample, columns);
        columns.forEach(c -> System.out.println(TAG + c.getName() + " " + c.getType() + " autogenerated=" + c.getIsAutogenerated()));
        return columns;
    }

    @Test
    public void everyValueKindGetsItsTypeLabel() {
        Document sample = new Document();
        sample.put("a_int", 1);
        sample.put("b_long", 2L);
        sample.put("c_double", 1.5d);
        sample.put("d_decimal", new Decimal128(new BigDecimal("1.25")));
        sample.put("e_string", "x");
        sample.put("f_id", new ObjectId());
        sample.put("g_list", List.of(1, 2));
        sample.put("h_date", new Date());
        sample.put("i_doc", new Document("k", "v"));
        sample.put("j_bool", true);
        sample.put("k_null", null);
        List<DatasourceStructure.Column> columns = columns(sample);
        assertEquals(List.of("Integer", "Long", "Double", "BigDecimal", "String", "ObjectId", "Array", "Date", "Object", "Object", "Object"),
                columns.stream().map(DatasourceStructure.Column::getType).toList());
        assertEquals(List.of("a_int", "b_long", "c_double", "d_decimal", "e_string", "f_id", "g_list", "h_date", "i_doc", "j_bool", "k_null"),
                columns.stream().map(DatasourceStructure.Column::getName).toList());
    }

    @Test
    public void onlyAnObjectIdIsAutogeneratedAndNoColumnHasADefault() {
        Document sample = new Document();
        sample.put("_id", new ObjectId());
        sample.put("name", "n");
        sample.put("n", 1);
        for (DatasourceStructure.Column column : columns(sample)) {
            assertEquals("_id".equals(column.getName()), column.getIsAutogenerated(), column.getName());
            assertEquals(null, column.getDefaultValue());
        }
    }

    @Test
    public void columnsAreSortedByNameWhateverTheDocumentOrder() {
        Document sample = new Document();
        sample.put("zeta", 1);
        sample.put("Alpha", 1);
        sample.put("mid", 1);
        sample.put("_id", new ObjectId());
        assertEquals(List.of("Alpha", "_id", "mid", "zeta"), columns(sample).stream().map(DatasourceStructure.Column::getName).toList());
    }

    @Test
    public void anEmptyDocumentGivesNoColumnsAndExistingColumnsAreKeptAndResorted() {
        assertTrue(columns(new Document()).isEmpty());
        ArrayList<DatasourceStructure.Column> existing = new ArrayList<>();
        existing.add(new DatasourceStructure.Column("z", "String", null, false));
        MongoQueryUtils.generateTemplatesAndStructureForACollection(new Document("a", 1), existing);
        assertEquals(List.of("a", "z"), existing.stream().map(DatasourceStructure.Column::getName).toList());
        assertFalse(existing.get(0).getIsAutogenerated());
    }

    @Test
    public void urlEncodeEscapesReservedCharactersAsUtf8() {
        assertEquals("p%40ss%3Aw%2Frd+%C3%A9", MongoQueryUtils.urlEncode("p@ss:w/rd é"));
        assertEquals("", MongoQueryUtils.urlEncode(""));
        assertEquals("plain-_.*", MongoQueryUtils.urlEncode("plain-_.*"));
    }
}
