package org.lowcoder.sdk.plugin.common.sql;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.ResultSet;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import org.junit.jupiter.api.Test;
import org.lowcoder.sdk.contract.FakeJdbc;
import org.lowcoder.sdk.contract.FakeJdbc.Column;
import org.lowcoder.sdk.models.DatasourceStructure.Table;
import org.lowcoder.sdk.models.DatasourceStructure.TableType;

/** {@link StructureParser}: the rows of the structure query (one per column) become tables with their columns. */
public class StructureParserTest {

    private static final List<Column> COLUMNS = List.of(new Column("table_name", "VARCHAR"), new Column("column_name", "VARCHAR"),
            new Column("data_type", "VARCHAR"));

    private static ResultSet rows(List<Object>... rows) {
        return FakeJdbc.resultSet(COLUMNS, List.of(rows));
    }

    @Test
    public void rowsAreGroupedIntoTablesWithTheirColumnsInRowOrder() throws Exception {
        ResultSet resultSet = rows(List.of("ORDERS", "ID", "NUMBER"), List.of("USERS", "NAME", "VARCHAR2"), List.of("ORDERS", "TOTAL", "NUMBER"),
                List.of("ORDERS", "CREATED", "DATE"));

        List<Table> tables = StructureParser.parseColumns(resultSet);

        Map<String, Table> byName = tables.stream().collect(Collectors.toMap(Table::getName, Function.identity()));
        System.out.println("[StructureParserTest] " + tables);
        assertEquals(2, tables.size());
        Table orders = byName.get("ORDERS");
        assertEquals(TableType.TABLE, orders.getType());
        assertNull(orders.getSchema());
        assertEquals(List.of("ID", "TOTAL", "CREATED"), orders.getColumns().stream().map(c -> c.getName()).toList());
        assertEquals(List.of("NUMBER", "NUMBER", "DATE"), orders.getColumns().stream().map(c -> c.getType()).toList());
        assertEquals(List.of(), orders.getKeys());
        assertEquals(List.of("NAME"), byName.get("USERS").getColumns().stream().map(c -> c.getName()).toList());
        assertNull(orders.getColumns().get(0).getDefaultValue());
        assertNull(orders.getColumns().get(0).getIsAutogenerated());
    }

    @Test
    public void anEmptyResultGivesNoTables() throws Exception {
        assertEquals(List.of(), StructureParser.parseColumns(rows()));
    }

    @Test
    public void theQueryNamesTheThreeAliasesTheParserReads() {
        for (String alias : new String[] {"as \"table_name\"", "as \"column_name\"", "as \"data_type\""}) {
            assertTrue(StructureParser.QUERY_STRUCTURE_SQL.contains(alias), alias);
        }
        assertTrue(StructureParser.QUERY_STRUCTURE_SQL.contains("hidden_column = 'NO'"), "hidden columns are left out");
    }
}
