import {
  AccountBookFilled,
  AccountBookOutlined,
  AccountBookTwoTone,
  AimOutlined,
  AlertFilled,
  AlertOutlined,
  AlertTwoTone,
  AlibabaOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  AlipayCircleFilled,
  AlipayCircleOutlined,
  AlipayOutlined,
  AlipaySquareFilled,
  AliwangwangFilled,
  AliwangwangOutlined,
  AliyunOutlined,
  AmazonCircleFilled,
  AmazonOutlined,
  AmazonSquareFilled,
  AndroidFilled,
  AndroidOutlined,
  AntCloudOutlined,
  AntDesignOutlined,
  ApartmentOutlined,
  ApiFilled,
  ApiOutlined,
  ApiTwoTone,
  AppleFilled,
  AppleOutlined,
  AppstoreAddOutlined,
  AppstoreFilled,
  AppstoreOutlined,
  AppstoreTwoTone,
  AreaChartOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  ArrowsAltOutlined,
  AudioFilled,
  AudioMutedOutlined,
  AudioOutlined,
  AudioTwoTone,
  AuditOutlined,
  BackwardFilled,
  BackwardOutlined,
  BankFilled,
  BankOutlined,
  BankTwoTone,
  BarChartOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BehanceCircleFilled,
  BehanceOutlined,
  BehanceSquareFilled,
  BehanceSquareOutlined,
  BellFilled,
  BellOutlined,
  BellTwoTone,
  BgColorsOutlined,
  BlockOutlined,
  BoldOutlined,
  BookFilled,
  BookOutlined,
  BookTwoTone,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  BorderInnerOutlined,
  BorderLeftOutlined,
  BorderOuterOutlined,
  BorderOutlined,
  BorderRightOutlined,
  BorderTopOutlined,
  BorderVerticleOutlined,
  BorderlessTableOutlined,
  BoxPlotFilled,
  BoxPlotOutlined,
  BoxPlotTwoTone,
  BranchesOutlined,
  BugFilled,
  BugOutlined,
  BugTwoTone,
  BuildFilled,
  BuildOutlined,
  BuildTwoTone,
  BulbFilled,
  BulbOutlined,
  BulbTwoTone,
  CalculatorFilled,
  CalculatorOutlined,
  CalculatorTwoTone,
  CalendarFilled,
  CalendarOutlined,
  CalendarTwoTone,
  CameraFilled,
  CameraOutlined,
  CameraTwoTone,
  CarFilled,
  CarOutlined,
  CarTwoTone,
  CaretDownFilled,
  CaretDownOutlined,
  CaretLeftFilled,
  CaretLeftOutlined,
  CaretRightFilled,
  CaretRightOutlined,
  CaretUpFilled,
  CaretUpOutlined,
  CarryOutFilled,
  CarryOutOutlined,
  CarryOutTwoTone,
  CheckCircleFilled,
  CheckCircleOutlined,
  CheckCircleTwoTone,
  CheckOutlined,
  CheckSquareFilled,
  CheckSquareOutlined,
  CheckSquareTwoTone,
  ChromeFilled,
  ChromeOutlined,
  CiCircleFilled,
  CiCircleOutlined,
  CiCircleTwoTone,
  CiOutlined,
  CiTwoTone,
  ClearOutlined,
  ClockCircleFilled,
  ClockCircleOutlined,
  ClockCircleTwoTone,
  CloseCircleFilled,
  CloseCircleOutlined,
  CloseCircleTwoTone,
  CloseOutlined,
  CloseSquareFilled,
  CloseSquareOutlined,
  CloseSquareTwoTone,
  CloudDownloadOutlined,
  CloudFilled,
  CloudOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudTwoTone,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeFilled,
  CodeOutlined,
  CodeSandboxCircleFilled,
  CodeSandboxOutlined,
  CodeSandboxSquareFilled,
  CodeTwoTone,
  CodepenCircleFilled,
  CodepenCircleOutlined,
  CodepenOutlined,
  CodepenSquareFilled,
  CoffeeOutlined,
  ColumnHeightOutlined,
  ColumnWidthOutlined,
  CommentOutlined,
  CompassFilled,
  CompassOutlined,
  CompassTwoTone,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsFilled,
  ContactsOutlined,
  ContactsTwoTone,
  ContainerFilled,
  ContainerOutlined,
  ContainerTwoTone,
  ControlFilled,
  ControlOutlined,
  ControlTwoTone,
  CopyFilled,
  CopyOutlined,
  CopyTwoTone,
  CopyrightCircleFilled,
  CopyrightCircleOutlined,
  CopyrightCircleTwoTone,
  CopyrightOutlined,
  CopyrightTwoTone,
  CreditCardFilled,
  CreditCardOutlined,
  CreditCardTwoTone,
  CrownFilled,
  CrownOutlined,
  CrownTwoTone,
  CustomerServiceFilled,
  CustomerServiceOutlined,
  CustomerServiceTwoTone,
  DashOutlined,
  DashboardFilled,
  DashboardOutlined,
  DashboardTwoTone,
  DatabaseFilled,
  DatabaseOutlined,
  DatabaseTwoTone,
  DeleteColumnOutlined,
  DeleteFilled,
  DeleteOutlined,
  DeleteRowOutlined,
  DeleteTwoTone,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DiffFilled,
  DiffOutlined,
  DiffTwoTone,
  DingdingOutlined,
  DingtalkCircleFilled,
  DingtalkOutlined,
  DingtalkSquareFilled,
  DisconnectOutlined,
  DislikeFilled,
  DislikeOutlined,
  DislikeTwoTone,
  DollarCircleFilled,
  DollarCircleOutlined,
  DollarCircleTwoTone,
  DollarOutlined,
  DollarTwoTone,
  DotChartOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  DownCircleFilled,
  DownCircleOutlined,
  DownCircleTwoTone,
  DownOutlined,
  DownSquareFilled,
  DownSquareOutlined,
  DownSquareTwoTone,
  DownloadOutlined,
  DragOutlined,
  DribbbleCircleFilled,
  DribbbleOutlined,
  DribbbleSquareFilled,
  DribbbleSquareOutlined,
  DropboxCircleFilled,
  DropboxOutlined,
  DropboxSquareFilled,
  EditFilled,
  EditOutlined,
  EditTwoTone,
  EllipsisOutlined,
  EnterOutlined,
  EnvironmentFilled,
  EnvironmentOutlined,
  EnvironmentTwoTone,
  EuroCircleFilled,
  EuroCircleOutlined,
  EuroCircleTwoTone,
  EuroOutlined,
  EuroTwoTone,
  ExceptionOutlined,
  ExclamationCircleFilled,
  ExclamationCircleOutlined,
  ExclamationCircleTwoTone,
  ExclamationOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentFilled,
  ExperimentOutlined,
  ExperimentTwoTone,
  ExportOutlined,
  EyeFilled,
  EyeInvisibleFilled,
  EyeInvisibleOutlined,
  EyeInvisibleTwoTone,
  EyeOutlined,
  EyeTwoTone,
  FacebookFilled,
  FacebookOutlined,
  FallOutlined,
  FastBackwardFilled,
  FastBackwardOutlined,
  FastForwardFilled,
  FastForwardOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddFilled,
  FileAddOutlined,
  FileAddTwoTone,
  FileDoneOutlined,
  FileExcelFilled,
  FileExcelOutlined,
  FileExcelTwoTone,
  FileExclamationFilled,
  FileExclamationOutlined,
  FileExclamationTwoTone,
  FileFilled,
  FileGifOutlined,
  FileImageFilled,
  FileImageOutlined,
  FileImageTwoTone,
  FileJpgOutlined,
  FileMarkdownFilled,
  FileMarkdownOutlined,
  FileMarkdownTwoTone,
  FileOutlined,
  FilePdfFilled,
  FilePdfOutlined,
  FilePdfTwoTone,
  FilePptFilled,
  FilePptOutlined,
  FilePptTwoTone,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextFilled,
  FileTextOutlined,
  FileTextTwoTone,
  FileTwoTone,
  FileUnknownFilled,
  FileUnknownOutlined,
  FileUnknownTwoTone,
  FileWordFilled,
  FileWordOutlined,
  FileWordTwoTone,
  FileZipFilled,
  FileZipOutlined,
  FileZipTwoTone,
  FilterFilled,
  FilterOutlined,
  FilterTwoTone,
  FireFilled,
  FireOutlined,
  FireTwoTone,
  FlagFilled,
  FlagOutlined,
  FlagTwoTone,
  FolderAddFilled,
  FolderAddOutlined,
  FolderAddTwoTone,
  FolderFilled,
  FolderOpenFilled,
  FolderOpenOutlined,
  FolderOpenTwoTone,
  FolderOutlined,
  FolderTwoTone,
  FolderViewOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  ForkOutlined,
  FormOutlined,
  FormatPainterFilled,
  FormatPainterOutlined,
  ForwardFilled,
  ForwardOutlined,
  FrownFilled,
  FrownOutlined,
  FrownTwoTone,
  FullscreenExitOutlined,
  FullscreenOutlined,
  FunctionOutlined,
  FundFilled,
  FundOutlined,
  FundProjectionScreenOutlined,
  FundTwoTone,
  FundViewOutlined,
  FunnelPlotFilled,
  FunnelPlotOutlined,
  FunnelPlotTwoTone,
  GatewayOutlined,
  GifOutlined,
  GiftFilled,
  GiftOutlined,
  GiftTwoTone,
  GithubFilled,
  GithubOutlined,
  GitlabFilled,
  GitlabOutlined,
  GlobalOutlined,
  GoldFilled,
  GoldOutlined,
  GoldTwoTone,
  GoldenFilled,
  GoogleCircleFilled,
  GoogleOutlined,
  GooglePlusCircleFilled,
  GooglePlusOutlined,
  GooglePlusSquareFilled,
  GoogleSquareFilled,
  GroupOutlined,
  HddFilled,
  HddOutlined,
  HddTwoTone,
  HeartFilled,
  HeartOutlined,
  HeartTwoTone,
  HeatMapOutlined,
  HighlightFilled,
  HighlightOutlined,
  HighlightTwoTone,
  HistoryOutlined,
  HolderOutlined,
  HomeFilled,
  HomeOutlined,
  HomeTwoTone,
  HourglassFilled,
  HourglassOutlined,
  HourglassTwoTone,
  Html5Filled,
  Html5Outlined,
  Html5TwoTone,
  IdcardFilled,
  IdcardOutlined,
  IdcardTwoTone,
  IeCircleFilled,
  IeOutlined,
  IeSquareFilled,
  ImportOutlined,
  InboxOutlined,
  InfoCircleFilled,
  InfoCircleOutlined,
  InfoCircleTwoTone,
  InfoOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InstagramFilled,
  InstagramOutlined,
  InsuranceFilled,
  InsuranceOutlined,
  InsuranceTwoTone,
  InteractionFilled,
  InteractionOutlined,
  InteractionTwoTone,
  IssuesCloseOutlined,
  ItalicOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutFilled,
  LayoutOutlined,
  LayoutTwoTone,
  LeftCircleFilled,
  LeftCircleOutlined,
  LeftCircleTwoTone,
  LeftOutlined,
  LeftSquareFilled,
  LeftSquareOutlined,
  LeftSquareTwoTone,
  LikeFilled,
  LikeOutlined,
  LikeTwoTone,
  LineChartOutlined,
  LineHeightOutlined,
  LineOutlined,
  LinkOutlined,
  LinkedinFilled,
  LinkedinOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockFilled,
  LockOutlined,
  LockTwoTone,
  LoginOutlined,
  LogoutOutlined,
  MacCommandFilled,
  MacCommandOutlined,
  MailFilled,
  MailOutlined,
  MailTwoTone,
  ManOutlined,
  MedicineBoxFilled,
  MedicineBoxOutlined,
  MedicineBoxTwoTone,
  MediumCircleFilled,
  MediumOutlined,
  MediumSquareFilled,
  MediumWorkmarkOutlined,
  MehFilled,
  MehOutlined,
  MehTwoTone,
  MenuFoldOutlined,
  MenuOutlined,
  MenuUnfoldOutlined,
  MergeCellsOutlined,
  MessageFilled,
  MessageOutlined,
  MessageTwoTone,
  MinusCircleFilled,
  MinusCircleOutlined,
  MinusCircleTwoTone,
  MinusOutlined,
  MinusSquareFilled,
  MinusSquareOutlined,
  MinusSquareTwoTone,
  MobileFilled,
  MobileOutlined,
  MobileTwoTone,
  MoneyCollectFilled,
  MoneyCollectOutlined,
  MoneyCollectTwoTone,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationFilled,
  NotificationOutlined,
  NotificationTwoTone,
  NumberOutlined,
  OneToOneOutlined,
  OrderedListOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PauseCircleFilled,
  PauseCircleOutlined,
  PauseCircleTwoTone,
  PauseOutlined,
  PayCircleFilled,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneFilled,
  PhoneOutlined,
  PhoneTwoTone,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  PictureFilled,
  PictureOutlined,
  PictureTwoTone,
  PieChartFilled,
  PieChartOutlined,
  PieChartTwoTone,
  PlayCircleFilled,
  PlayCircleOutlined,
  PlayCircleTwoTone,
  PlaySquareFilled,
  PlaySquareOutlined,
  PlaySquareTwoTone,
  PlusCircleFilled,
  PlusCircleOutlined,
  PlusCircleTwoTone,
  PlusOutlined,
  PlusSquareFilled,
  PlusSquareOutlined,
  PlusSquareTwoTone,
  PoundCircleFilled,
  PoundCircleOutlined,
  PoundCircleTwoTone,
  PoundOutlined,
  PoweroffOutlined,
  PrinterFilled,
  PrinterOutlined,
  PrinterTwoTone,
  ProfileFilled,
  ProfileOutlined,
  ProfileTwoTone,
  ProjectFilled,
  ProjectOutlined,
  ProjectTwoTone,
  PropertySafetyFilled,
  PropertySafetyOutlined,
  PropertySafetyTwoTone,
  PullRequestOutlined,
  PushpinFilled,
  PushpinOutlined,
  PushpinTwoTone,
  QqCircleFilled,
  QqOutlined,
  QqSquareFilled,
  QrcodeOutlined,
  QuestionCircleFilled,
  QuestionCircleOutlined,
  QuestionCircleTwoTone,
  QuestionOutlined,
  RadarChartOutlined,
  RadiusBottomleftOutlined,
  RadiusBottomrightOutlined,
  RadiusSettingOutlined,
  RadiusUpleftOutlined,
  RadiusUprightOutlined,
  ReadFilled,
  ReadOutlined,
  ReconciliationFilled,
  ReconciliationOutlined,
  ReconciliationTwoTone,
  RedEnvelopeFilled,
  RedEnvelopeOutlined,
  RedEnvelopeTwoTone,
  RedditCircleFilled,
  RedditOutlined,
  RedditSquareFilled,
  RedoOutlined,
  ReloadOutlined,
  RestFilled,
  RestOutlined,
  RestTwoTone,
  RetweetOutlined,
  RightCircleFilled,
  RightCircleOutlined,
  RightCircleTwoTone,
  RightOutlined,
  RightSquareFilled,
  RightSquareOutlined,
  RightSquareTwoTone,
  RiseOutlined,
  RobotFilled,
  RobotOutlined,
  RocketFilled,
  RocketOutlined,
  RocketTwoTone,
  RollbackOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateFilled,
  SafetyCertificateOutlined,
  SafetyCertificateTwoTone,
  SafetyOutlined,
  SaveFilled,
  SaveOutlined,
  SaveTwoTone,
  ScanOutlined,
  ScheduleFilled,
  ScheduleOutlined,
  ScheduleTwoTone,
  ScissorOutlined,
  SearchOutlined,
  SecurityScanFilled,
  SecurityScanOutlined,
  SecurityScanTwoTone,
  SelectOutlined,
  SendOutlined,
  SettingFilled,
  SettingOutlined,
  SettingTwoTone,
  ShakeOutlined,
  ShareAltOutlined,
  ShopFilled,
  ShopOutlined,
  ShopTwoTone,
  ShoppingCartOutlined,
  ShoppingFilled,
  ShoppingOutlined,
  ShoppingTwoTone,
  ShrinkOutlined,
  SignalFilled,
  SisternodeOutlined,
  SketchCircleFilled,
  SketchOutlined,
  SketchSquareFilled,
  SkinFilled,
  SkinOutlined,
  SkinTwoTone,
  SkypeFilled,
  SkypeOutlined,
  SlackCircleFilled,
  SlackOutlined,
  SlackSquareFilled,
  SlackSquareOutlined,
  SlidersFilled,
  SlidersOutlined,
  SlidersTwoTone,
  SmallDashOutlined,
  SmileFilled,
  SmileOutlined,
  SmileTwoTone,
  SnippetsFilled,
  SnippetsOutlined,
  SnippetsTwoTone,
  SolutionOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  SoundFilled,
  SoundOutlined,
  SoundTwoTone,
  SplitCellsOutlined,
  StarFilled,
  StarOutlined,
  StarTwoTone,
  StepBackwardFilled,
  StepBackwardOutlined,
  StepForwardFilled,
  StepForwardOutlined,
  StockOutlined,
  StopFilled,
  StopOutlined,
  StopTwoTone,
  StrikethroughOutlined,
  SubnodeOutlined,
  SwapLeftOutlined,
  SwapOutlined,
  SwapRightOutlined,
  SwitcherFilled,
  SwitcherOutlined,
  SwitcherTwoTone,
  SyncOutlined,
  TableOutlined,
  TabletFilled,
  TabletOutlined,
  TabletTwoTone,
  TagFilled,
  TagOutlined,
  TagTwoTone,
  TagsFilled,
  TagsOutlined,
  TagsTwoTone,
  TaobaoCircleFilled,
  TaobaoCircleOutlined,
  TaobaoOutlined,
  TaobaoSquareFilled,
  TeamOutlined,
  ThunderboltFilled,
  ThunderboltOutlined,
  ThunderboltTwoTone,
  ToTopOutlined,
  ToolFilled,
  ToolOutlined,
  ToolTwoTone,
  TrademarkCircleFilled,
  TrademarkCircleOutlined,
  TrademarkCircleTwoTone,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyFilled,
  TrophyOutlined,
  TrophyTwoTone,
  TwitterCircleFilled,
  TwitterOutlined,
  TwitterSquareFilled,
  UnderlineOutlined,
  UndoOutlined,
  UngroupOutlined,
  UnlockFilled,
  UnlockOutlined,
  UnlockTwoTone,
  UnorderedListOutlined,
  UpCircleFilled,
  UpCircleOutlined,
  UpCircleTwoTone,
  UpOutlined,
  UpSquareFilled,
  UpSquareOutlined,
  UpSquareTwoTone,
  UploadOutlined,
  UsbFilled,
  UsbOutlined,
  UsbTwoTone,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VerticalAlignBottomOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignTopOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VideoCameraAddOutlined,
  VideoCameraFilled,
  VideoCameraOutlined,
  VideoCameraTwoTone,
  WalletFilled,
  WalletOutlined,
  WalletTwoTone,
  WarningFilled,
  WarningOutlined,
  WarningTwoTone,
  WechatFilled,
  WechatOutlined,
  WeiboCircleFilled,
  WeiboCircleOutlined,
  WeiboOutlined,
  WeiboSquareFilled,
  WeiboSquareOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WindowsFilled,
  WindowsOutlined,
  WomanOutlined,
  YahooFilled,
  YahooOutlined,
  YoutubeFilled,
  YoutubeOutlined,
  YuqueFilled,
  YuqueOutlined,
  ZhihuCircleFilled,
  ZhihuOutlined,
  ZhihuSquareFilled,
  ZoomInOutlined,
  ZoomOutOutlined,
} from "@ant-design/icons";

export const ANTDICON = {
  accountbookfilled: <AccountBookFilled />,
  accountbookoutlined: <AccountBookOutlined />,
  accountbooktwotone: <AccountBookTwoTone />,
  aimoutlined: <AimOutlined />,
  alertfilled: <AlertFilled />,
  alertoutlined: <AlertOutlined />,
  alerttwotone: <AlertTwoTone />,
  alibabaoutlined: <AlibabaOutlined />,
  aligncenteroutlined: <AlignCenterOutlined />,
  alignleftoutlined: <AlignLeftOutlined />,
  alignrightoutlined: <AlignRightOutlined />,
  alipaycirclefilled: <AlipayCircleFilled />,
  alipaycircleoutlined: <AlipayCircleOutlined />,
  alipayoutlined: <AlipayOutlined />,
  alipaysquarefilled: <AlipaySquareFilled />,
  aliwangwangfilled: <AliwangwangFilled />,
  aliwangwangoutlined: <AliwangwangOutlined />,
  aliyunoutlined: <AliyunOutlined />,
  amazoncirclefilled: <AmazonCircleFilled />,
  amazonoutlined: <AmazonOutlined />,
  amazonsquarefilled: <AmazonSquareFilled />,
  androidfilled: <AndroidFilled />,
  androidoutlined: <AndroidOutlined />,
  antcloudoutlined: <AntCloudOutlined />,
  antdesignoutlined: <AntDesignOutlined />,
  apartmentoutlined: <ApartmentOutlined />,
  apifilled: <ApiFilled />,
  apioutlined: <ApiOutlined />,
  apitwotone: <ApiTwoTone />,
  applefilled: <AppleFilled />,
  appleoutlined: <AppleOutlined />,
  appstoreaddoutlined: <AppstoreAddOutlined />,
  appstorefilled: <AppstoreFilled />,
  appstoreoutlined: <AppstoreOutlined />,
  appstoretwotone: <AppstoreTwoTone />,
  areachartoutlined: <AreaChartOutlined />,
  arrowdownoutlined: <ArrowDownOutlined />,
  arrowleftoutlined: <ArrowLeftOutlined />,
  arrowrightoutlined: <ArrowRightOutlined />,
  arrowupoutlined: <ArrowUpOutlined />,
  arrowsaltoutlined: <ArrowsAltOutlined />,
  audiofilled: <AudioFilled />,
  audiomutedoutlined: <AudioMutedOutlined />,
  audiooutlined: <AudioOutlined />,
  audiotwotone: <AudioTwoTone />,
  auditoutlined: <AuditOutlined />,
  backwardfilled: <BackwardFilled />,
  backwardoutlined: <BackwardOutlined />,
  bankfilled: <BankFilled />,
  bankoutlined: <BankOutlined />,
  banktwotone: <BankTwoTone />,
  barchartoutlined: <BarChartOutlined />,
  barcodeoutlined: <BarcodeOutlined />,
  barsoutlined: <BarsOutlined />,
  behancecirclefilled: <BehanceCircleFilled />,
  behanceoutlined: <BehanceOutlined />,
  behancesquarefilled: <BehanceSquareFilled />,
  behancesquareoutlined: <BehanceSquareOutlined />,
  bellfilled: <BellFilled />,
  belloutlined: <BellOutlined />,
  belltwotone: <BellTwoTone />,
  bgcolorsoutlined: <BgColorsOutlined />,
  blockoutlined: <BlockOutlined />,
  boldoutlined: <BoldOutlined />,
  bookfilled: <BookFilled />,
  bookoutlined: <BookOutlined />,
  booktwotone: <BookTwoTone />,
  borderbottomoutlined: <BorderBottomOutlined />,
  borderhorizontaloutlined: <BorderHorizontalOutlined />,
  borderinneroutlined: <BorderInnerOutlined />,
  borderleftoutlined: <BorderLeftOutlined />,
  borderouteroutlined: <BorderOuterOutlined />,
  borderoutlined: <BorderOutlined />,
  borderrightoutlined: <BorderRightOutlined />,
  bordertopoutlined: <BorderTopOutlined />,
  borderverticleoutlined: <BorderVerticleOutlined />,
  borderlesstableoutlined: <BorderlessTableOutlined />,
  boxplotfilled: <BoxPlotFilled />,
  boxplotoutlined: <BoxPlotOutlined />,
  boxplottwotone: <BoxPlotTwoTone />,
  branchesoutlined: <BranchesOutlined />,
  bugfilled: <BugFilled />,
  bugoutlined: <BugOutlined />,
  bugtwotone: <BugTwoTone />,
  buildfilled: <BuildFilled />,
  buildoutlined: <BuildOutlined />,
  buildtwotone: <BuildTwoTone />,
  bulbfilled: <BulbFilled />,
  bulboutlined: <BulbOutlined />,
  bulbtwotone: <BulbTwoTone />,
  calculatorfilled: <CalculatorFilled />,
  calculatoroutlined: <CalculatorOutlined />,
  calculatortwotone: <CalculatorTwoTone />,
  calendarfilled: <CalendarFilled />,
  calendaroutlined: <CalendarOutlined />,
  calendartwotone: <CalendarTwoTone />,
  camerafilled: <CameraFilled />,
  cameraoutlined: <CameraOutlined />,
  cameratwotone: <CameraTwoTone />,
  carfilled: <CarFilled />,
  caroutlined: <CarOutlined />,
  cartwotone: <CarTwoTone />,
  caretdownfilled: <CaretDownFilled />,
  caretdownoutlined: <CaretDownOutlined />,
  caretleftfilled: <CaretLeftFilled />,
  caretleftoutlined: <CaretLeftOutlined />,
  caretrightfilled: <CaretRightFilled />,
  caretrightoutlined: <CaretRightOutlined />,
  caretupfilled: <CaretUpFilled />,
  caretupoutlined: <CaretUpOutlined />,
  carryoutfilled: <CarryOutFilled />,
  carryoutoutlined: <CarryOutOutlined />,
  carryouttwotone: <CarryOutTwoTone />,
  checkcirclefilled: <CheckCircleFilled />,
  checkcircleoutlined: <CheckCircleOutlined />,
  checkcircletwotone: <CheckCircleTwoTone />,
  checkoutlined: <CheckOutlined />,
  checksquarefilled: <CheckSquareFilled />,
  checksquareoutlined: <CheckSquareOutlined />,
  checksquaretwotone: <CheckSquareTwoTone />,
  chromefilled: <ChromeFilled />,
  chromeoutlined: <ChromeOutlined />,
  cicirclefilled: <CiCircleFilled />,
  cicircleoutlined: <CiCircleOutlined />,
  cicircletwotone: <CiCircleTwoTone />,
  cioutlined: <CiOutlined />,
  citwotone: <CiTwoTone />,
  clearoutlined: <ClearOutlined />,
  clockcirclefilled: <ClockCircleFilled />,
  clockcircleoutlined: <ClockCircleOutlined />,
  clockcircletwotone: <ClockCircleTwoTone />,
  closecirclefilled: <CloseCircleFilled />,
  closecircleoutlined: <CloseCircleOutlined />,
  closecircletwotone: <CloseCircleTwoTone />,
  closeoutlined: <CloseOutlined />,
  closesquarefilled: <CloseSquareFilled />,
  closesquareoutlined: <CloseSquareOutlined />,
  closesquaretwotone: <CloseSquareTwoTone />,
  clouddownloadoutlined: <CloudDownloadOutlined />,
  cloudfilled: <CloudFilled />,
  cloudoutlined: <CloudOutlined />,
  cloudserveroutlined: <CloudServerOutlined />,
  cloudsyncoutlined: <CloudSyncOutlined />,
  cloudtwotone: <CloudTwoTone />,
  clouduploadoutlined: <CloudUploadOutlined />,
  clusteroutlined: <ClusterOutlined />,
  codefilled: <CodeFilled />,
  codeoutlined: <CodeOutlined />,
  codesandboxcirclefilled: <CodeSandboxCircleFilled />,
  codesandboxoutlined: <CodeSandboxOutlined />,
  codesandboxsquarefilled: <CodeSandboxSquareFilled />,
  codetwotone: <CodeTwoTone />,
  codepencirclefilled: <CodepenCircleFilled />,
  codepencircleoutlined: <CodepenCircleOutlined />,
  codepenoutlined: <CodepenOutlined />,
  codepensquarefilled: <CodepenSquareFilled />,
  coffeeoutlined: <CoffeeOutlined />,
  columnheightoutlined: <ColumnHeightOutlined />,
  columnwidthoutlined: <ColumnWidthOutlined />,
  commentoutlined: <CommentOutlined />,
  compassfilled: <CompassFilled />,
  compassoutlined: <CompassOutlined />,
  compasstwotone: <CompassTwoTone />,
  compressoutlined: <CompressOutlined />,
  consolesqloutlined: <ConsoleSqlOutlined />,
  contactsfilled: <ContactsFilled />,
  contactsoutlined: <ContactsOutlined />,
  contactstwotone: <ContactsTwoTone />,
  containerfilled: <ContainerFilled />,
  containeroutlined: <ContainerOutlined />,
  containertwotone: <ContainerTwoTone />,
  controlfilled: <ControlFilled />,
  controloutlined: <ControlOutlined />,
  controltwotone: <ControlTwoTone />,
  copyfilled: <CopyFilled />,
  copyoutlined: <CopyOutlined />,
  copytwotone: <CopyTwoTone />,
  copyrightcirclefilled: <CopyrightCircleFilled />,
  copyrightcircleoutlined: <CopyrightCircleOutlined />,
  copyrightcircletwotone: <CopyrightCircleTwoTone />,
  copyrightoutlined: <CopyrightOutlined />,
  copyrighttwotone: <CopyrightTwoTone />,
  creditcardfilled: <CreditCardFilled />,
  creditcardoutlined: <CreditCardOutlined />,
  creditcardtwotone: <CreditCardTwoTone />,
  crownfilled: <CrownFilled />,
  crownoutlined: <CrownOutlined />,
  crowntwotone: <CrownTwoTone />,
  customerservicefilled: <CustomerServiceFilled />,
  customerserviceoutlined: <CustomerServiceOutlined />,
  customerservicetwotone: <CustomerServiceTwoTone />,
  dashoutlined: <DashOutlined />,
  dashboardfilled: <DashboardFilled />,
  dashboardoutlined: <DashboardOutlined />,
  dashboardtwotone: <DashboardTwoTone />,
  databasefilled: <DatabaseFilled />,
  databaseoutlined: <DatabaseOutlined />,
  databasetwotone: <DatabaseTwoTone />,
  deletecolumnoutlined: <DeleteColumnOutlined />,
  deletefilled: <DeleteFilled />,
  deleteoutlined: <DeleteOutlined />,
  deleterowoutlined: <DeleteRowOutlined />,
  deletetwotone: <DeleteTwoTone />,
  deliveredprocedureoutlined: <DeliveredProcedureOutlined />,
  deploymentunitoutlined: <DeploymentUnitOutlined />,
  desktopoutlined: <DesktopOutlined />,
  difffilled: <DiffFilled />,
  diffoutlined: <DiffOutlined />,
  difftwotone: <DiffTwoTone />,
  dingdingoutlined: <DingdingOutlined />,
  dingtalkcirclefilled: <DingtalkCircleFilled />,
  dingtalkoutlined: <DingtalkOutlined />,
  dingtalksquarefilled: <DingtalkSquareFilled />,
  disconnectoutlined: <DisconnectOutlined />,
  dislikefilled: <DislikeFilled />,
  dislikeoutlined: <DislikeOutlined />,
  disliketwotone: <DislikeTwoTone />,
  dollarcirclefilled: <DollarCircleFilled />,
  dollarcircleoutlined: <DollarCircleOutlined />,
  dollarcircletwotone: <DollarCircleTwoTone />,
  dollaroutlined: <DollarOutlined />,
  dollartwotone: <DollarTwoTone />,
  dotchartoutlined: <DotChartOutlined />,
  doubleleftoutlined: <DoubleLeftOutlined />,
  doublerightoutlined: <DoubleRightOutlined />,
  downcirclefilled: <DownCircleFilled />,
  downcircleoutlined: <DownCircleOutlined />,
  downcircletwotone: <DownCircleTwoTone />,
  downoutlined: <DownOutlined />,
  downsquarefilled: <DownSquareFilled />,
  downsquareoutlined: <DownSquareOutlined />,
  downsquaretwotone: <DownSquareTwoTone />,
  downloadoutlined: <DownloadOutlined />,
  dragoutlined: <DragOutlined />,
  dribbblecirclefilled: <DribbbleCircleFilled />,
  dribbbleoutlined: <DribbbleOutlined />,
  dribbblesquarefilled: <DribbbleSquareFilled />,
  dribbblesquareoutlined: <DribbbleSquareOutlined />,
  dropboxcirclefilled: <DropboxCircleFilled />,
  dropboxoutlined: <DropboxOutlined />,
  dropboxsquarefilled: <DropboxSquareFilled />,
  editfilled: <EditFilled />,
  editoutlined: <EditOutlined />,
  edittwotone: <EditTwoTone />,
  ellipsisoutlined: <EllipsisOutlined />,
  enteroutlined: <EnterOutlined />,
  environmentfilled: <EnvironmentFilled />,
  environmentoutlined: <EnvironmentOutlined />,
  environmenttwotone: <EnvironmentTwoTone />,
  eurocirclefilled: <EuroCircleFilled />,
  eurocircleoutlined: <EuroCircleOutlined />,
  eurocircletwotone: <EuroCircleTwoTone />,
  eurooutlined: <EuroOutlined />,
  eurotwotone: <EuroTwoTone />,
  exceptionoutlined: <ExceptionOutlined />,
  exclamationcirclefilled: <ExclamationCircleFilled />,
  exclamationcircleoutlined: <ExclamationCircleOutlined />,
  exclamationcircletwotone: <ExclamationCircleTwoTone />,
  exclamationoutlined: <ExclamationOutlined />,
  expandaltoutlined: <ExpandAltOutlined />,
  expandoutlined: <ExpandOutlined />,
  experimentfilled: <ExperimentFilled />,
  experimentoutlined: <ExperimentOutlined />,
  experimenttwotone: <ExperimentTwoTone />,
  exportoutlined: <ExportOutlined />,
  eyefilled: <EyeFilled />,
  eyeinvisiblefilled: <EyeInvisibleFilled />,
  eyeinvisibleoutlined: <EyeInvisibleOutlined />,
  eyeinvisibletwotone: <EyeInvisibleTwoTone />,
  eyeoutlined: <EyeOutlined />,
  eyetwotone: <EyeTwoTone />,
  facebookfilled: <FacebookFilled />,
  facebookoutlined: <FacebookOutlined />,
  falloutlined: <FallOutlined />,
  fastbackwardfilled: <FastBackwardFilled />,
  fastbackwardoutlined: <FastBackwardOutlined />,
  fastforwardfilled: <FastForwardFilled />,
  fastforwardoutlined: <FastForwardOutlined />,
  fieldbinaryoutlined: <FieldBinaryOutlined />,
  fieldnumberoutlined: <FieldNumberOutlined />,
  fieldstringoutlined: <FieldStringOutlined />,
  fieldtimeoutlined: <FieldTimeOutlined />,
  fileaddfilled: <FileAddFilled />,
  fileaddoutlined: <FileAddOutlined />,
  fileaddtwotone: <FileAddTwoTone />,
  filedoneoutlined: <FileDoneOutlined />,
  fileexcelfilled: <FileExcelFilled />,
  fileexceloutlined: <FileExcelOutlined />,
  fileexceltwotone: <FileExcelTwoTone />,
  fileexclamationfilled: <FileExclamationFilled />,
  fileexclamationoutlined: <FileExclamationOutlined />,
  fileexclamationtwotone: <FileExclamationTwoTone />,
  filefilled: <FileFilled />,
  filegifoutlined: <FileGifOutlined />,
  fileimagefilled: <FileImageFilled />,
  fileimageoutlined: <FileImageOutlined />,
  fileimagetwotone: <FileImageTwoTone />,
  filejpgoutlined: <FileJpgOutlined />,
  filemarkdownfilled: <FileMarkdownFilled />,
  filemarkdownoutlined: <FileMarkdownOutlined />,
  filemarkdowntwotone: <FileMarkdownTwoTone />,
  fileoutlined: <FileOutlined />,
  filepdffilled: <FilePdfFilled />,
  filepdfoutlined: <FilePdfOutlined />,
  filepdftwotone: <FilePdfTwoTone />,
  filepptfilled: <FilePptFilled />,
  filepptoutlined: <FilePptOutlined />,
  fileppttwotone: <FilePptTwoTone />,
  fileprotectoutlined: <FileProtectOutlined />,
  filesearchoutlined: <FileSearchOutlined />,
  filesyncoutlined: <FileSyncOutlined />,
  filetextfilled: <FileTextFilled />,
  filetextoutlined: <FileTextOutlined />,
  filetexttwotone: <FileTextTwoTone />,
  filetwotone: <FileTwoTone />,
  fileunknownfilled: <FileUnknownFilled />,
  fileunknownoutlined: <FileUnknownOutlined />,
  fileunknowntwotone: <FileUnknownTwoTone />,
  filewordfilled: <FileWordFilled />,
  filewordoutlined: <FileWordOutlined />,
  filewordtwotone: <FileWordTwoTone />,
  filezipfilled: <FileZipFilled />,
  filezipoutlined: <FileZipOutlined />,
  fileziptwotone: <FileZipTwoTone />,
  filterfilled: <FilterFilled />,
  filteroutlined: <FilterOutlined />,
  filtertwotone: <FilterTwoTone />,
  firefilled: <FireFilled />,
  fireoutlined: <FireOutlined />,
  firetwotone: <FireTwoTone />,
  flagfilled: <FlagFilled />,
  flagoutlined: <FlagOutlined />,
  flagtwotone: <FlagTwoTone />,
  folderaddfilled: <FolderAddFilled />,
  folderaddoutlined: <FolderAddOutlined />,
  folderaddtwotone: <FolderAddTwoTone />,
  folderfilled: <FolderFilled />,
  folderopenfilled: <FolderOpenFilled />,
  folderopenoutlined: <FolderOpenOutlined />,
  folderopentwotone: <FolderOpenTwoTone />,
  folderoutlined: <FolderOutlined />,
  foldertwotone: <FolderTwoTone />,
  folderviewoutlined: <FolderViewOutlined />,
  fontcolorsoutlined: <FontColorsOutlined />,
  fontsizeoutlined: <FontSizeOutlined />,
  forkoutlined: <ForkOutlined />,
  formoutlined: <FormOutlined />,
  formatpainterfilled: <FormatPainterFilled />,
  formatpainteroutlined: <FormatPainterOutlined />,
  forwardfilled: <ForwardFilled />,
  forwardoutlined: <ForwardOutlined />,
  frownfilled: <FrownFilled />,
  frownoutlined: <FrownOutlined />,
  frowntwotone: <FrownTwoTone />,
  fullscreenexitoutlined: <FullscreenExitOutlined />,
  fullscreenoutlined: <FullscreenOutlined />,
  functionoutlined: <FunctionOutlined />,
  fundfilled: <FundFilled />,
  fundoutlined: <FundOutlined />,
  fundprojectionscreenoutlined: <FundProjectionScreenOutlined />,
  fundtwotone: <FundTwoTone />,
  fundviewoutlined: <FundViewOutlined />,
  funnelplotfilled: <FunnelPlotFilled />,
  funnelplotoutlined: <FunnelPlotOutlined />,
  funnelplottwotone: <FunnelPlotTwoTone />,
  gatewayoutlined: <GatewayOutlined />,
  gifoutlined: <GifOutlined />,
  giftfilled: <GiftFilled />,
  giftoutlined: <GiftOutlined />,
  gifttwotone: <GiftTwoTone />,
  githubfilled: <GithubFilled />,
  githuboutlined: <GithubOutlined />,
  gitlabfilled: <GitlabFilled />,
  gitlaboutlined: <GitlabOutlined />,
  globaloutlined: <GlobalOutlined />,
  goldfilled: <GoldFilled />,
  goldoutlined: <GoldOutlined />,
  goldtwotone: <GoldTwoTone />,
  goldenfilled: <GoldenFilled />,
  googlecirclefilled: <GoogleCircleFilled />,
  googleoutlined: <GoogleOutlined />,
  googlepluscirclefilled: <GooglePlusCircleFilled />,
  googleplusoutlined: <GooglePlusOutlined />,
  googleplussquarefilled: <GooglePlusSquareFilled />,
  googlesquarefilled: <GoogleSquareFilled />,
  groupoutlined: <GroupOutlined />,
  hddfilled: <HddFilled />,
  hddoutlined: <HddOutlined />,
  hddtwotone: <HddTwoTone />,
  heartfilled: <HeartFilled />,
  heartoutlined: <HeartOutlined />,
  hearttwotone: <HeartTwoTone />,
  heatmapoutlined: <HeatMapOutlined />,
  highlightfilled: <HighlightFilled />,
  highlightoutlined: <HighlightOutlined />,
  highlighttwotone: <HighlightTwoTone />,
  historyoutlined: <HistoryOutlined />,
  holderoutlined: <HolderOutlined />,
  homefilled: <HomeFilled />,
  homeoutlined: <HomeOutlined />,
  hometwotone: <HomeTwoTone />,
  hourglassfilled: <HourglassFilled />,
  hourglassoutlined: <HourglassOutlined />,
  hourglasstwotone: <HourglassTwoTone />,
  html5filled: <Html5Filled />,
  html5outlined: <Html5Outlined />,
  html5twotone: <Html5TwoTone />,
  idcardfilled: <IdcardFilled />,
  idcardoutlined: <IdcardOutlined />,
  idcardtwotone: <IdcardTwoTone />,
  iecirclefilled: <IeCircleFilled />,
  ieoutlined: <IeOutlined />,
  iesquarefilled: <IeSquareFilled />,
  importoutlined: <ImportOutlined />,
  inboxoutlined: <InboxOutlined />,
  infocirclefilled: <InfoCircleFilled />,
  infocircleoutlined: <InfoCircleOutlined />,
  infocircletwotone: <InfoCircleTwoTone />,
  infooutlined: <InfoOutlined />,
  insertrowaboveoutlined: <InsertRowAboveOutlined />,
  insertrowbelowoutlined: <InsertRowBelowOutlined />,
  insertrowleftoutlined: <InsertRowLeftOutlined />,
  insertrowrightoutlined: <InsertRowRightOutlined />,
  instagramfilled: <InstagramFilled />,
  instagramoutlined: <InstagramOutlined />,
  insurancefilled: <InsuranceFilled />,
  insuranceoutlined: <InsuranceOutlined />,
  insurancetwotone: <InsuranceTwoTone />,
  interactionfilled: <InteractionFilled />,
  interactionoutlined: <InteractionOutlined />,
  interactiontwotone: <InteractionTwoTone />,
  issuescloseoutlined: <IssuesCloseOutlined />,
  italicoutlined: <ItalicOutlined />,
  keyoutlined: <KeyOutlined />,
  laptopoutlined: <LaptopOutlined />,
  layoutfilled: <LayoutFilled />,
  layoutoutlined: <LayoutOutlined />,
  layouttwotone: <LayoutTwoTone />,
  leftcirclefilled: <LeftCircleFilled />,
  leftcircleoutlined: <LeftCircleOutlined />,
  leftcircletwotone: <LeftCircleTwoTone />,
  leftoutlined: <LeftOutlined />,
  leftsquarefilled: <LeftSquareFilled />,
  leftsquareoutlined: <LeftSquareOutlined />,
  leftsquaretwotone: <LeftSquareTwoTone />,
  likefilled: <LikeFilled />,
  likeoutlined: <LikeOutlined />,
  liketwotone: <LikeTwoTone />,
  linechartoutlined: <LineChartOutlined />,
  lineheightoutlined: <LineHeightOutlined />,
  lineoutlined: <LineOutlined />,
  linkoutlined: <LinkOutlined />,
  linkedinfilled: <LinkedinFilled />,
  linkedinoutlined: <LinkedinOutlined />,
  loading3quartersoutlined: <Loading3QuartersOutlined />,
  loadingoutlined: <LoadingOutlined />,
  lockfilled: <LockFilled />,
  lockoutlined: <LockOutlined />,
  locktwotone: <LockTwoTone />,
  loginoutlined: <LoginOutlined />,
  logoutoutlined: <LogoutOutlined />,
  maccommandfilled: <MacCommandFilled />,
  maccommandoutlined: <MacCommandOutlined />,
  mailfilled: <MailFilled />,
  mailoutlined: <MailOutlined />,
  mailtwotone: <MailTwoTone />,
  manoutlined: <ManOutlined />,
  medicineboxfilled: <MedicineBoxFilled />,
  medicineboxoutlined: <MedicineBoxOutlined />,
  medicineboxtwotone: <MedicineBoxTwoTone />,
  mediumcirclefilled: <MediumCircleFilled />,
  mediumoutlined: <MediumOutlined />,
  mediumsquarefilled: <MediumSquareFilled />,
  mediumworkmarkoutlined: <MediumWorkmarkOutlined />,
  mehfilled: <MehFilled />,
  mehoutlined: <MehOutlined />,
  mehtwotone: <MehTwoTone />,
  menufoldoutlined: <MenuFoldOutlined />,
  menuoutlined: <MenuOutlined />,
  menuunfoldoutlined: <MenuUnfoldOutlined />,
  mergecellsoutlined: <MergeCellsOutlined />,
  messagefilled: <MessageFilled />,
  messageoutlined: <MessageOutlined />,
  messagetwotone: <MessageTwoTone />,
  minuscirclefilled: <MinusCircleFilled />,
  minuscircleoutlined: <MinusCircleOutlined />,
  minuscircletwotone: <MinusCircleTwoTone />,
  minusoutlined: <MinusOutlined />,
  minussquarefilled: <MinusSquareFilled />,
  minussquareoutlined: <MinusSquareOutlined />,
  minussquaretwotone: <MinusSquareTwoTone />,
  mobilefilled: <MobileFilled />,
  mobileoutlined: <MobileOutlined />,
  mobiletwotone: <MobileTwoTone />,
  moneycollectfilled: <MoneyCollectFilled />,
  moneycollectoutlined: <MoneyCollectOutlined />,
  moneycollecttwotone: <MoneyCollectTwoTone />,
  monitoroutlined: <MonitorOutlined />,
  moreoutlined: <MoreOutlined />,
  nodecollapseoutlined: <NodeCollapseOutlined />,
  nodeexpandoutlined: <NodeExpandOutlined />,
  nodeindexoutlined: <NodeIndexOutlined />,
  notificationfilled: <NotificationFilled />,
  notificationoutlined: <NotificationOutlined />,
  notificationtwotone: <NotificationTwoTone />,
  numberoutlined: <NumberOutlined />,
  onetooneoutlined: <OneToOneOutlined />,
  orderedlistoutlined: <OrderedListOutlined />,
  paperclipoutlined: <PaperClipOutlined />,
  partitionoutlined: <PartitionOutlined />,
  pausecirclefilled: <PauseCircleFilled />,
  pausecircleoutlined: <PauseCircleOutlined />,
  pausecircletwotone: <PauseCircleTwoTone />,
  pauseoutlined: <PauseOutlined />,
  paycirclefilled: <PayCircleFilled />,
  paycircleoutlined: <PayCircleOutlined />,
  percentageoutlined: <PercentageOutlined />,
  phonefilled: <PhoneFilled />,
  phoneoutlined: <PhoneOutlined />,
  phonetwotone: <PhoneTwoTone />,
  piccenteroutlined: <PicCenterOutlined />,
  picleftoutlined: <PicLeftOutlined />,
  picrightoutlined: <PicRightOutlined />,
  picturefilled: <PictureFilled />,
  pictureoutlined: <PictureOutlined />,
  picturetwotone: <PictureTwoTone />,
  piechartfilled: <PieChartFilled />,
  piechartoutlined: <PieChartOutlined />,
  piecharttwotone: <PieChartTwoTone />,
  playcirclefilled: <PlayCircleFilled />,
  playcircleoutlined: <PlayCircleOutlined />,
  playcircletwotone: <PlayCircleTwoTone />,
  playsquarefilled: <PlaySquareFilled />,
  playsquareoutlined: <PlaySquareOutlined />,
  playsquaretwotone: <PlaySquareTwoTone />,
  pluscirclefilled: <PlusCircleFilled />,
  pluscircleoutlined: <PlusCircleOutlined />,
  pluscircletwotone: <PlusCircleTwoTone />,
  plusoutlined: <PlusOutlined />,
  plussquarefilled: <PlusSquareFilled />,
  plussquareoutlined: <PlusSquareOutlined />,
  plussquaretwotone: <PlusSquareTwoTone />,
  poundcirclefilled: <PoundCircleFilled />,
  poundcircleoutlined: <PoundCircleOutlined />,
  poundcircletwotone: <PoundCircleTwoTone />,
  poundoutlined: <PoundOutlined />,
  poweroffoutlined: <PoweroffOutlined />,
  printerfilled: <PrinterFilled />,
  printeroutlined: <PrinterOutlined />,
  printertwotone: <PrinterTwoTone />,
  profilefilled: <ProfileFilled />,
  profileoutlined: <ProfileOutlined />,
  profiletwotone: <ProfileTwoTone />,
  projectfilled: <ProjectFilled />,
  projectoutlined: <ProjectOutlined />,
  projecttwotone: <ProjectTwoTone />,
  propertysafetyfilled: <PropertySafetyFilled />,
  propertysafetyoutlined: <PropertySafetyOutlined />,
  propertysafetytwotone: <PropertySafetyTwoTone />,
  pullrequestoutlined: <PullRequestOutlined />,
  pushpinfilled: <PushpinFilled />,
  pushpinoutlined: <PushpinOutlined />,
  pushpintwotone: <PushpinTwoTone />,
  qqcirclefilled: <QqCircleFilled />,
  qqoutlined: <QqOutlined />,
  qqsquarefilled: <QqSquareFilled />,
  qrcodeoutlined: <QrcodeOutlined />,
  questioncirclefilled: <QuestionCircleFilled />,
  questioncircleoutlined: <QuestionCircleOutlined />,
  questioncircletwotone: <QuestionCircleTwoTone />,
  questionoutlined: <QuestionOutlined />,
  radarchartoutlined: <RadarChartOutlined />,
  radiusbottomleftoutlined: <RadiusBottomleftOutlined />,
  radiusbottomrightoutlined: <RadiusBottomrightOutlined />,
  radiussettingoutlined: <RadiusSettingOutlined />,
  radiusupleftoutlined: <RadiusUpleftOutlined />,
  radiusuprightoutlined: <RadiusUprightOutlined />,
  readfilled: <ReadFilled />,
  readoutlined: <ReadOutlined />,
  reconciliationfilled: <ReconciliationFilled />,
  reconciliationoutlined: <ReconciliationOutlined />,
  reconciliationtwotone: <ReconciliationTwoTone />,
  redenvelopefilled: <RedEnvelopeFilled />,
  redenvelopeoutlined: <RedEnvelopeOutlined />,
  redenvelopetwotone: <RedEnvelopeTwoTone />,
  redditcirclefilled: <RedditCircleFilled />,
  redditoutlined: <RedditOutlined />,
  redditsquarefilled: <RedditSquareFilled />,
  redooutlined: <RedoOutlined />,
  reloadoutlined: <ReloadOutlined />,
  restfilled: <RestFilled />,
  restoutlined: <RestOutlined />,
  resttwotone: <RestTwoTone />,
  retweetoutlined: <RetweetOutlined />,
  rightcirclefilled: <RightCircleFilled />,
  rightcircleoutlined: <RightCircleOutlined />,
  rightcircletwotone: <RightCircleTwoTone />,
  rightoutlined: <RightOutlined />,
  rightsquarefilled: <RightSquareFilled />,
  rightsquareoutlined: <RightSquareOutlined />,
  rightsquaretwotone: <RightSquareTwoTone />,
  riseoutlined: <RiseOutlined />,
  robotfilled: <RobotFilled />,
  robotoutlined: <RobotOutlined />,
  rocketfilled: <RocketFilled />,
  rocketoutlined: <RocketOutlined />,
  rockettwotone: <RocketTwoTone />,
  rollbackoutlined: <RollbackOutlined />,
  rotateleftoutlined: <RotateLeftOutlined />,
  rotaterightoutlined: <RotateRightOutlined />,
  safetycertificatefilled: <SafetyCertificateFilled />,
  safetycertificateoutlined: <SafetyCertificateOutlined />,
  safetycertificatetwotone: <SafetyCertificateTwoTone />,
  safetyoutlined: <SafetyOutlined />,
  savefilled: <SaveFilled />,
  saveoutlined: <SaveOutlined />,
  savetwotone: <SaveTwoTone />,
  scanoutlined: <ScanOutlined />,
  schedulefilled: <ScheduleFilled />,
  scheduleoutlined: <ScheduleOutlined />,
  scheduletwotone: <ScheduleTwoTone />,
  scissoroutlined: <ScissorOutlined />,
  searchoutlined: <SearchOutlined />,
  securityscanfilled: <SecurityScanFilled />,
  securityscanoutlined: <SecurityScanOutlined />,
  securityscantwotone: <SecurityScanTwoTone />,
  selectoutlined: <SelectOutlined />,
  sendoutlined: <SendOutlined />,
  settingfilled: <SettingFilled />,
  settingoutlined: <SettingOutlined />,
  settingtwotone: <SettingTwoTone />,
  shakeoutlined: <ShakeOutlined />,
  sharealtoutlined: <ShareAltOutlined />,
  shopfilled: <ShopFilled />,
  shopoutlined: <ShopOutlined />,
  shoptwotone: <ShopTwoTone />,
  shoppingcartoutlined: <ShoppingCartOutlined />,
  shoppingfilled: <ShoppingFilled />,
  shoppingoutlined: <ShoppingOutlined />,
  shoppingtwotone: <ShoppingTwoTone />,
  shrinkoutlined: <ShrinkOutlined />,
  signalfilled: <SignalFilled />,
  sisternodeoutlined: <SisternodeOutlined />,
  sketchcirclefilled: <SketchCircleFilled />,
  sketchoutlined: <SketchOutlined />,
  sketchsquarefilled: <SketchSquareFilled />,
  skinfilled: <SkinFilled />,
  skinoutlined: <SkinOutlined />,
  skintwotone: <SkinTwoTone />,
  skypefilled: <SkypeFilled />,
  skypeoutlined: <SkypeOutlined />,
  slackcirclefilled: <SlackCircleFilled />,
  slackoutlined: <SlackOutlined />,
  slacksquarefilled: <SlackSquareFilled />,
  slacksquareoutlined: <SlackSquareOutlined />,
  slidersfilled: <SlidersFilled />,
  slidersoutlined: <SlidersOutlined />,
  sliderstwotone: <SlidersTwoTone />,
  smalldashoutlined: <SmallDashOutlined />,
  smilefilled: <SmileFilled />,
  smileoutlined: <SmileOutlined />,
  smiletwotone: <SmileTwoTone />,
  snippetsfilled: <SnippetsFilled />,
  snippetsoutlined: <SnippetsOutlined />,
  snippetstwotone: <SnippetsTwoTone />,
  solutionoutlined: <SolutionOutlined />,
  sortascendingoutlined: <SortAscendingOutlined />,
  sortdescendingoutlined: <SortDescendingOutlined />,
  soundfilled: <SoundFilled />,
  soundoutlined: <SoundOutlined />,
  soundtwotone: <SoundTwoTone />,
  splitcellsoutlined: <SplitCellsOutlined />,
  starfilled: <StarFilled />,
  staroutlined: <StarOutlined />,
  startwotone: <StarTwoTone />,
  stepbackwardfilled: <StepBackwardFilled />,
  stepbackwardoutlined: <StepBackwardOutlined />,
  stepforwardfilled: <StepForwardFilled />,
  stepforwardoutlined: <StepForwardOutlined />,
  stockoutlined: <StockOutlined />,
  stopfilled: <StopFilled />,
  stopoutlined: <StopOutlined />,
  stoptwotone: <StopTwoTone />,
  strikethroughoutlined: <StrikethroughOutlined />,
  subnodeoutlined: <SubnodeOutlined />,
  swapleftoutlined: <SwapLeftOutlined />,
  swapoutlined: <SwapOutlined />,
  swaprightoutlined: <SwapRightOutlined />,
  switcherfilled: <SwitcherFilled />,
  switcheroutlined: <SwitcherOutlined />,
  switchertwotone: <SwitcherTwoTone />,
  syncoutlined: <SyncOutlined />,
  tableoutlined: <TableOutlined />,
  tabletfilled: <TabletFilled />,
  tabletoutlined: <TabletOutlined />,
  tablettwotone: <TabletTwoTone />,
  tagfilled: <TagFilled />,
  tagoutlined: <TagOutlined />,
  tagtwotone: <TagTwoTone />,
  tagsfilled: <TagsFilled />,
  tagsoutlined: <TagsOutlined />,
  tagstwotone: <TagsTwoTone />,
  taobaocirclefilled: <TaobaoCircleFilled />,
  taobaocircleoutlined: <TaobaoCircleOutlined />,
  taobaooutlined: <TaobaoOutlined />,
  taobaosquarefilled: <TaobaoSquareFilled />,
  teamoutlined: <TeamOutlined />,
  thunderboltfilled: <ThunderboltFilled />,
  thunderboltoutlined: <ThunderboltOutlined />,
  thunderbolttwotone: <ThunderboltTwoTone />,
  totopoutlined: <ToTopOutlined />,
  toolfilled: <ToolFilled />,
  tooloutlined: <ToolOutlined />,
  tooltwotone: <ToolTwoTone />,
  trademarkcirclefilled: <TrademarkCircleFilled />,
  trademarkcircleoutlined: <TrademarkCircleOutlined />,
  trademarkcircletwotone: <TrademarkCircleTwoTone />,
  trademarkoutlined: <TrademarkOutlined />,
  transactionoutlined: <TransactionOutlined />,
  translationoutlined: <TranslationOutlined />,
  trophyfilled: <TrophyFilled />,
  trophyoutlined: <TrophyOutlined />,
  trophytwotone: <TrophyTwoTone />,
  twittercirclefilled: <TwitterCircleFilled />,
  twitteroutlined: <TwitterOutlined />,
  twittersquarefilled: <TwitterSquareFilled />,
  underlineoutlined: <UnderlineOutlined />,
  undooutlined: <UndoOutlined />,
  ungroupoutlined: <UngroupOutlined />,
  unlockfilled: <UnlockFilled />,
  unlockoutlined: <UnlockOutlined />,
  unlocktwotone: <UnlockTwoTone />,
  unorderedlistoutlined: <UnorderedListOutlined />,
  upcirclefilled: <UpCircleFilled />,
  upcircleoutlined: <UpCircleOutlined />,
  upcircletwotone: <UpCircleTwoTone />,
  upoutlined: <UpOutlined />,
  upsquarefilled: <UpSquareFilled />,
  upsquareoutlined: <UpSquareOutlined />,
  upsquaretwotone: <UpSquareTwoTone />,
  uploadoutlined: <UploadOutlined />,
  usbfilled: <UsbFilled />,
  usboutlined: <UsbOutlined />,
  usbtwotone: <UsbTwoTone />,
  useraddoutlined: <UserAddOutlined />,
  userdeleteoutlined: <UserDeleteOutlined />,
  useroutlined: <UserOutlined />,
  userswitchoutlined: <UserSwitchOutlined />,
  usergroupaddoutlined: <UsergroupAddOutlined />,
  usergroupdeleteoutlined: <UsergroupDeleteOutlined />,
  verifiedoutlined: <VerifiedOutlined />,
  verticalalignbottomoutlined: <VerticalAlignBottomOutlined />,
  verticalalignmiddleoutlined: <VerticalAlignMiddleOutlined />,
  verticalaligntopoutlined: <VerticalAlignTopOutlined />,
  verticalleftoutlined: <VerticalLeftOutlined />,
  verticalrightoutlined: <VerticalRightOutlined />,
  videocameraaddoutlined: <VideoCameraAddOutlined />,
  videocamerafilled: <VideoCameraFilled />,
  videocameraoutlined: <VideoCameraOutlined />,
  videocameratwotone: <VideoCameraTwoTone />,
  walletfilled: <WalletFilled />,
  walletoutlined: <WalletOutlined />,
  wallettwotone: <WalletTwoTone />,
  warningfilled: <WarningFilled />,
  warningoutlined: <WarningOutlined />,
  warningtwotone: <WarningTwoTone />,
  wechatfilled: <WechatFilled />,
  wechatoutlined: <WechatOutlined />,
  weibocirclefilled: <WeiboCircleFilled />,
  weibocircleoutlined: <WeiboCircleOutlined />,
  weibooutlined: <WeiboOutlined />,
  weibosquarefilled: <WeiboSquareFilled />,
  weibosquareoutlined: <WeiboSquareOutlined />,
  whatsappoutlined: <WhatsAppOutlined />,
  wifioutlined: <WifiOutlined />,
  windowsfilled: <WindowsFilled />,
  windowsoutlined: <WindowsOutlined />,
  womanoutlined: <WomanOutlined />,
  yahoofilled: <YahooFilled />,
  yahoooutlined: <YahooOutlined />,
  youtubefilled: <YoutubeFilled />,
  youtubeoutlined: <YoutubeOutlined />,
  yuquefilled: <YuqueFilled />,
  yuqueoutlined: <YuqueOutlined />,
  zhihucirclefilled: <ZhihuCircleFilled />,
  zhihuoutlined: <ZhihuOutlined />,
  zhihusquarefilled: <ZhihuSquareFilled />,
  zoominoutlined: <ZoomInOutlined />,
  zoomoutoutlined: <ZoomOutOutlined />,
};