package org.lowcoder.plugin.sql;

import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.lowcoder.sdk.models.QueryExecutionResult;
import org.lowcoder.sdk.plugin.common.sql.HikariPerfWrapper;
import org.lowcoder.sdk.plugin.common.sql.SqlBasedQueryExecutionContext;

import java.sql.Connection;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.lowcoder.plugin.sql.H2SqlTestSupport.assertPluginError;
import static org.lowcoder.sdk.exception.PluginCommonError.QUERY_EXECUTION_ERROR;

/**
 * Unit SB-4 (task L5-1): prepared versus plain statements, generated keys, error wrapping and connection hand-back of
 * {@link GeneralSqlExecutor} / {@link SqlBasedQueryExecutor#blockingExecuteQuery}, on H2.
 */
public class GeneralSqlExecutorStatementTest {

    static final String TABLE = "stmt_keys";
    static final String VALUE = "v";
    static final String INVALID_SQL = "selec nothing from nowhere";
    static final String QUOTED_VALUE = "x' || 'y";
    static final String POOL_NAME = "GeneralSqlExecutorStatementTest";
    static final int FAILING_RUNS = 3;

    private static final String URL = H2SqlTestSupport.newUrl("stmt");
    private static Connection connection;

    @BeforeAll
    static void open() {
        connection = H2SqlTestSupport.open(URL);
    }

    @AfterAll
    static void close() throws Exception {
        connection.close();
    }

    @BeforeEach
    void freshTable() {
        H2SqlTestSupport.run(connection, "drop table if exists " + TABLE,
                "create table " + TABLE + " (id bigint generated by default as identity, v varchar(50))");
    }

    private static SqlBasedQueryExecutionContext context(String sql, Map<String, Object> params, boolean disablePreparedStatement) {
        return SqlBasedQueryExecutionContext.builder().query(sql).requestParams(params).disablePreparedStatement(disablePreparedStatement).build();
    }

    @Test
    public void disabledPreparedStatementRendersTheValueIntoTheSqlText() {
        String sql = "select '{{" + VALUE + "}}' as v";
        Map<String, Object> params = Map.of(VALUE, QUOTED_VALUE);
        Object prepared = rowValue(new GeneralSqlExecutor().execute(connection, context(sql, params, false)));
        Object plain = rowValue(new GeneralSqlExecutor().execute(connection, context(sql, params, true)));
        assertEquals(QUOTED_VALUE, prepared, "bound: the value stays one literal");
        assertEquals("xy", plain, "rendered: the value became part of the SQL text");
        System.out.println("[GeneralSqlExecutorStatementTest] bound -> " + prepared + " ; rendered into the SQL -> " + plain);
    }

    private static Object rowValue(QueryExecutionResult result) {
        @SuppressWarnings("unchecked")
        List<Map<String, Object>> rows = (List<Map<String, Object>>) result.getData();
        assertEquals(1, rows.size());
        return rows.get(0).get(VALUE);
    }

    @Test
    public void generatedKeysAreReturnedOnTheCapablePathsAndOmittedWhenNotSupported() {
        String insert = "insert into " + TABLE + " (v) values ('a')";
        Map<String, Object> keyed = Map.of("affectedRows", 1, "generatedKeys", List.of(1L));
        assertEquals(keyed, new GeneralSqlExecutor(true).execute(connection, context(insert, Map.of(), true)).getData(), "plain, supported");
        assertEquals(Map.of("affectedRows", 1), new GeneralSqlExecutor(false).execute(connection, context(insert, Map.of(), true)).getData(),
                "plain, generated keys not supported (the Snowflake variant)");
        QueryExecutionResult prepared = new GeneralSqlExecutor().execute(connection,
                context("insert into " + TABLE + " (v) values ({{v}})", Map.of(VALUE, "b"), false));
        assertEquals(Map.of("affectedRows", 1, "generatedKeys", List.of(3L)), prepared.getData(), "prepared");
        System.out.println("[GeneralSqlExecutorStatementTest] keys: " + keyed + " ; none when unsupported ; prepared " + prepared.getData());
    }

    @Test
    public void invalidSqlIsWrappedAsQueryExecutionErrorInBothModes() {
        for (boolean plain : new boolean[] {false, true}) {
            assertPluginError(QUERY_EXECUTION_ERROR, H2SqlTestSupport.QUERY_ERROR_KEY,
                    () -> new GeneralSqlExecutor().execute(connection, context(INVALID_SQL, Map.of(), plain)));
        }
        System.out.println("[GeneralSqlExecutorStatementTest] invalid SQL gave QUERY_EXECUTION_ERROR (prepared and plain)");
    }

    @Test
    public void connectionsGoBackToThePoolAfterSuccessAndAfterFailure() {
        H2SqlTestSupport.H2Connector connector = new H2SqlTestSupport.H2Connector(URL, H2SqlTestSupport.H2_DRIVER, POOL_NAME, 2);
        H2SqlTestSupport.H2Executor executor = new H2SqlTestSupport.H2Executor(new GeneralSqlExecutor());
        HikariPerfWrapper wrapper = connector.blockingCreateConnection(new H2SqlTestSupport.H2Config("h", "d", false, null));
        try {
            for (int i = 0; i < FAILING_RUNS; i++) {
                assertPluginError(QUERY_EXECUTION_ERROR, H2SqlTestSupport.QUERY_ERROR_KEY,
                        () -> executor.blockingExecuteQuery(wrapper, context(INVALID_SQL, Map.of(), false)));
            }
            assertEquals(0, wrapper.getActiveConnections(), "a failed statement must not keep its connection");
            executor.blockingExecuteQuery(wrapper, context("select 1 as v", Map.of(), false));
            assertEquals(0, wrapper.getActiveConnections(), "a finished statement must not keep its connection");
            System.out.println("[GeneralSqlExecutorStatementTest] active connections after " + FAILING_RUNS + " failures and one success: "
                    + wrapper.getActiveConnections() + " of " + wrapper.getTotalConnections());
        } finally {
            connector.blockingDestroyConnection(wrapper);
        }
        assertTrue(((HikariDataSource) wrapper.getHikariDataSource()).isClosed());
        assertFalse(((HikariDataSource) wrapper.getHikariDataSource()).isRunning());
    }
}
