/**
 * Represents a Workspace entity in an environment
 */
export interface Workspace {
    id: string;
    name: string;
    role: string; // 'admin', 'member', etc.
    creationDate?: number; // timestamp
    status: string; // 'ACTIVE', 'INACTIVE', etc.
    // Optional fields
    gid?: string;
    createdBy?: string;
    isAutoGeneratedOrganization?: boolean | null;
    logoUrl?: string;
    managed?: boolean;
  }