import { remoteComp } from "../../comps/comps/remoteComp/remoteComp";
import {
  registerComp,
  type UICompType,
  type UICompManifest
} from "../../comps/uiCompRegistry";
import { RemoteCompInfo } from "@lowcoder-ee/types/remoteComp";

type Registry = {
  [key in UICompType]?: UICompManifest;
};

const builtInRemoteComps: Omit<RemoteCompInfo, "compName"> = {
  source: "npm",
  isRemote: true,
  packageName: "lowcoder-comps",
};

export var uiCompMap: Registry = {
  // Dashboards

  // charts
  chart: {
    name: "",
    enName: "Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    comp: remoteComp({ ...builtInRemoteComps, compName: "chart" }),
    keywords: "",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },

  basicChart: {
    name: "",
    enName: "Basic Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    comp: remoteComp({ ...builtInRemoteComps, compName: "basicChart" }),
    keywords: "",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },

  candleStickChart: {
    name: "",
    enName: "Candlestick Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "candleStickChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  funnelChart: {
    name: "",
    enName: "Sankey Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "funnelChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  gaugeChart: {
    name: "",
    enName: "Candlestick Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "gaugeChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  graphChart: {
    name: "",
    enName: "Graph Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "graphChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  heatmapChart: {
    name: "",
    enName: "Heatmap Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "heatmapChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  radarChart: {
    name: "",
    enName: "Radar Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "radarChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  sankeyChart: {
    name: "",
    enName: "Sankey Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "sankeyChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  sunburstChart: {
    name: "",
    enName: "Sunburst Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "sunburstChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  themeriverChart: {
    name: "",
    enName: "Theme River Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "themeriverChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  treeChart: {
    name: "",
    enName: "Tree Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "treeChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  treemapChart: {
    name: "",
    enName: "Treemap Chart",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "treemapChart" }),
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },

  // GeoMap

  openLayersGeoMap: {
    name: "",
    enName: "OpenLayersGeoMap",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({
      compName: "geo",
      packageName: "lowcoder-comp-geo",
      source: "npm",
      isRemote: true,
    }),
    compName: "lowcoder-comp-geo",
    layoutInfo: {
      w: 12,
      h: 50,
    },
  },
  chartsGeoMap: {
    name: "",
    enName: "GeoMap",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "chartsGeoMap" }),
    layoutInfo: {
      w: 19,
      h: 60,
    },
  },

  table: {
    name: "",
    enName: "Table",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "TableComp",
    compPath: "comps/tableComp/index",
    layoutInfo: {
      w: 12,
      h: 40,
    },
    withoutLoading: true,
    defaultDataFnName: "defaultTableData",
    defaultDataFnPath: "comps/tableComp/mockTableComp",
  },

  pivotTable: {
    name: "",
    enName: "pivotTable",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    comp: remoteComp({
      compName: "pivottable",
      packageName: "lowcoder-comp-reactpivottable",
      source: "npm",
      isRemote: true,
    }),
    compName: "lowcoder-comp-reactpivottable",
    layoutInfo: {
      w: 12,
      h: 50,
    },
  },

  mermaid: {
    name: "",
    enName: "Mermaid Charts",
    comp: remoteComp({ ...builtInRemoteComps, compName: "mermaid" }),
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  timeline: {
    name: "",
    enName: "timeline",
    description: "",
    categories: ["dashboards"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "TimeLineComp",
    compPath: "comps/timelineComp/timelineComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },

  // Layout

  responsiveLayout: {
    name: "",
    enName: "Responsive Layout",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ResponsiveLayoutComp",
    compPath: "comps/responsiveLayout/index",
    withoutLoading: true,
    layoutInfo: {
      w: 24,
      h: 25,
      delayCollision: true,
    },
  },
  pageLayout: {
    name: "",
    enName: "Page Layout Container",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "PageLayoutComp",
    compPath: "comps/containerComp/pageLayoutComp",
    withoutLoading: true,
    layoutInfo: {
      w: 12,
      h: 50,
      // static: true,
      delayCollision: true,
    },
    defaultDataFnName: "defaultPageLayoutData",
    defaultDataFnPath: "comps/tableComp/mockTableComp",
  },
  columnLayout: {
    name: "Column Layout",
    enName: "Column Layout",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ColumnLayoutComp",
    compPath: "comps/columnLayout/index",
    withoutLoading: true,
    layoutInfo: {
      w: 24,
      h: 25,
      delayCollision: true,
    },
  },
  floatTextContainer: {
    name: "",
    enName: "Container",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ContainerComp",
    compPath: "comps/containerComp/textContainerComp",
    withoutLoading: true,
    layoutInfo: {
      w: 12,
      h: 25,
      // static: true,
      delayCollision: true,
    },
    defaultDataFnName: "defaultContainerData",
    defaultDataFnPath: "comps/containerComp/containerComp",
  },
  card: {
    name: "",
    enName: "card",
    icon: null,
    description: "",
    categories: ["layout"],
    keywords: "",
    lazyLoad: true,
    compName: "CardComp",
    compPath: "comps/containerComp/cardComp",
    layoutInfo: {
      h: 44,
      w: 6,
    },
  },
  tabbedContainer: {
    name: "",
    enName: "Tabbed Container",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "TabbedContainerComp",
    compPath: "comps/tabs/index",
    withoutLoading: true,
    layoutInfo: {
      w: 12,
      h: 25,
      // static: true,
      delayCollision: true,
    },
  },
  collapsibleContainer: {
    name: "",
    enName: "Collapsible Container",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ContainerComp",
    compPath: "comps/containerComp/containerComp",
    withoutLoading: true,
    layoutInfo: {
      w: 12,
      h: 25,
      // static: true,
      delayCollision: true,
    },
    defaultDataFnName: "defaultCollapsibleContainerData",
    defaultDataFnPath: "comps/containerComp/collapsibleContainerComp",
  },
  container: {
    name: "",
    enName: "Container",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ContainerComp",
    compPath: "comps/containerComp/containerComp",
    withoutLoading: true,
    layoutInfo: {
      w: 12,
      h: 25,
      // static: true,
      delayCollision: true,
    },
    defaultDataFnName: "defaultContainerData",
    defaultDataFnPath: "comps/containerComp/containerComp",
  },
  listView: {
    name: "",
    enName: "List View",
    icon: null,
    description: "",
    categories: ["layout"],
    keywords: "",
    lazyLoad: true,
    compName: "ListViewComp",
    compPath: "comps/listViewComp/index",
    layoutInfo: {
      w: 12,
      h: 40,
      delayCollision: true,
    },
    defaultDataFnName: "defaultListViewData",
    defaultDataFnPath: "comps/listViewComp/index",
  },
  grid: {
    name: "",
    enName: "Grid",
    icon: null,
    description: "",
    categories: ["layout"],
    keywords: "",
    lazyLoad: true,
    compName: "GridComp",
    compPath: "comps/listViewComp/index",
    layoutInfo: {
      w: 12,
      h: 40,
      delayCollision: true,
    },
    defaultDataFnName: "defaultGridData",
    defaultDataFnPath: "comps/listViewComp/index",
  },
  modal: {
    name: "",
    enName: "Modal",
    icon: null,
    description: "",
    categories: ["layout"],
    keywords: "",
    lazyLoad: true,
    compName: "ModalComp",
    compPath: "hooks/modalComp",
    withoutLoading: true,
  },
  drawer: {
    name: "",
    enName: "Drawer",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "DrawerComp",
    compPath: "hooks/drawerComp",
    withoutLoading: true,
  },
  divider: {
    name: "",
    enName: "Divider",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "DividerComp",
    compPath: "comps/dividerComp",
    layoutInfo: {
      w: 12,
      h: 1,
    },
  },
  navigation: {
    name: "",
    enName: "Navigation",
    description: "",
    icon: null,
    categories: ["layout"],
    keywords: "",
    lazyLoad: true,
    compName: "NavComp",
    compPath: "comps/navComp/navComp",
    layoutInfo: {
      w: 24,
      h: 5,
    },
  },
  step: {
    name: "",
    enName: "Steps Control",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "StepComp",
    compPath: "comps/selectInputComp/stepControl",
    layoutInfo: {
      w: 19,
      h: 6,
    },
  },
  cascader: {
    name: "",
    enName: "Cascader",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "CascaderWithDefault",
    compPath: "comps/selectInputComp/cascaderComp",
    layoutInfo: {
      w: 9,
      h: 5,
    },
  },
  link: {
    name: "",
    enName: "Link",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "LinkComp",
    compPath: "comps/buttonComp/linkComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },
  floatingButton: {
    name: "",
    enName: "floatingButton",
    description: "",
    categories: ["layout"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "FloatButtonComp",
    compPath: "comps/buttonComp/floatButtonComp",
    layoutInfo: {
      w: 1,
      h: 1,
    },
    withoutLoading: true,
  },

  // Scheduling

  calendar: {
    name: "",
    enName: "Calendar",
    description: "",
    categories: ["scheduling", "projectmanagement"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "calendar" }),
    layoutInfo: {
      w: 19,
      h: 60,
    },
  },
  timer: {
    name: "",
    enName: "timer",
    icon: null,
    description: "",
    categories: ["scheduling", "projectmanagement"],
    keywords: "",
    lazyLoad: true,
    compName: "TimerComp",
    compPath: "comps/timerComp",
    layoutInfo: {
      h: 14,
      w: 6,
    },
  },

  // Meeting & Collaboration

  sharingcomponent: {
    name: "",
    enName: "Sharing",
    description: "",
    categories: ["collaboration"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "meetingSharing" }),
    withoutLoading: true,
    layoutInfo: {
      w: 12,
      h: 50,
    },
  },
  videocomponent: {
    name: "",
    enName: "Video",
    description: "",
    categories: ["collaboration"],
    icon: null,
    keywords: "",
    comp: remoteComp({ ...builtInRemoteComps, compName: "meetingStream" }),
    withoutLoading: true,
    layoutInfo: {
      w: 6,
      h: 32,
    },
  },
  meeting: {
    name: "",
    enName: "Drawer",
    comp: remoteComp({ ...builtInRemoteComps, compName: "meetingController" }),
    description: "",
    categories: ["collaboration"],
    icon: null,
    keywords: "",
    withoutLoading: true,
  },

  // added by Mousheng
  avatar: {
    name: "",
    enName: "avatar",
    description: "",
    categories: ["collaboration"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "AvatarComp",
    compPath: "comps/avatar",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },

  avatarGroup: {
    name: "",
    enName: "avatarGroup",
    icon: null,
    description: "",
    categories: ["collaboration"],
    keywords: "",
    lazyLoad: true,
    compName: "AvatarGroupComp",
    compPath: "comps/avatarGroup",
    withoutLoading: true,
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },

  comment: {
    name: "",
    enName: "comment",
    description: "",
    categories: ["collaboration"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "CommentComp",
    compPath: "comps/commentComp/commentComp",
    layoutInfo: {
      w: 12,
      h: 55,
    },
  },
  mention: {
    name: "",
    enName: "mention",
    description: "",
    categories: ["collaboration"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "MentionComp",
    compPath: "comps/textInputComp/mentionComp",
  },

  // Forms

  form: {
    name: "",
    enName: "Form",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "FormComp",
    compPath: "comps/formComp/formComp",
    withoutLoading: true,
    layoutInfo: {
      w: 12,
      h: 50,
      // static: true,
      delayCollision: true,
    },
    defaultDataFnName: "defaultFormData",
    defaultDataFnPath: "comps/formComp/formComp",
  },
  jsonSchemaForm: {
    name: "",
    enName: "JSON Schema Form",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "JsonSchemaFormComp",
    compPath: "comps/jsonSchemaFormComp/jsonSchemaFormComp",
    layoutInfo: {
      w: 12,
      h: 50,
    },
  },
  jsonEditor: {
    name: "",
    enName: "JSON Editor",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "JsonEditorComp",
    compPath: "comps/jsonComp/jsonEditorComp",
    layoutInfo: {
      w: 12,
      h: 50,
    },
  },
  jsonExplorer: {
    name: "",
    enName: "JSON Explorer",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "JsonExplorerComp",
    compPath: "comps/jsonComp/jsonExplorerComp",
    layoutInfo: {
      w: 12,
      h: 50,
    },
  },
  richTextEditor: {
    name: "",
    enName: "Rich Text Editor",
    categories: ["forms"],
    description: "",
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "RichTextEditorComp",
    compPath: "comps/richTextEditorComp",
    layoutInfo: {
      w: 12,
      h: 50,
    },
  },
  input: {
    name: "",
    enName: "Input",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "InputComp",
    compPath: "comps/textInputComp/inputComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },
  password: {
    name: "",
    enName: "Password",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "PasswordComp",
    compPath: "comps/textInputComp/passwordComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },
  numberInput: {
    name: "",
    enName: "Number Input",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "NumberInputComp",
    compPath: "comps/numberInputComp/numberInputComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },
  textArea: {
    name: "",
    enName: "Text Area",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "TextAreaComp",
    compPath: "comps/textInputComp/textAreaComp",
    layoutInfo: {
      w: 6,
      h: 12,
    },
  },
  autocomplete: {
    name: "",
    enName: "autoComplete",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "AutoCompleteComp",
    compPath: "comps/autoCompleteComp/autoCompleteComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },
  switch: {
    name: "",
    enName: "Switch",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "SwitchComp",
    compPath: "comps/switchComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },
  checkbox: {
    name: "",
    enName: "Checkbox",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "CheckboxComp",
    compPath: "comps/selectInputComp/checkboxComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },
  radio: {
    name: "",
    enName: "Radio",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "RadioComp",
    compPath: "comps/selectInputComp/radioComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },
  date: {
    name: "",
    enName: "Date",
    description: "",
    categories: ["forms", "scheduling"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "DatePickerComp",
    compPath: "comps/dateComp/dateComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },
  dateRange: {
    name: "",
    enName: "Date Range",
    description: "",
    categories: ["forms", "scheduling"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "DateRangeComp",
    compPath: "comps/dateComp/dateComp",
    layoutInfo: {
      w: 12,
      h: 6,
    },
  },
  time: {
    name: "",
    enName: "Time",
    description: "",
    categories: ["forms", "scheduling"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "TimePickerComp",
    compPath: "comps/dateComp/timeComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },
  timeRange: {
    name: "",
    enName: "Time Range",
    categories: ["forms", "scheduling"],
    description: "",
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "TimeRangeComp",
    compPath: "comps/dateComp/timeComp",
    layoutInfo: {
      w: 12,
      h: 6,
    },
  },

  slider: {
    name: "",
    enName: "Slider",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "SliderComp",
    compPath: "comps/numberInputComp/sliderComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },
  rangeSlider: {
    name: "",
    enName: "Range Slider",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "RangeSliderComp",
    compPath: "comps/numberInputComp/rangeSliderComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },

  button: {
    name: "",
    enName: "Button",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ButtonComp",
    compPath: "comps/buttonComp/buttonComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
    withoutLoading: true,
  },
  controlButton: {
    name: "",
    enName: "Controls",
    description: "",
    categories: ["forms", "collaboration"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ControlButton",
    compPath: "comps/meetingComp/controlButton",
    withoutLoading: true,
    layoutInfo: {
      w: 3,
      h: 6,
    },
  },
  dropdown: {
    name: "",
    enName: "Dropdown",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "DropdownComp",
    compPath: "comps/buttonComp/dropdownComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },
  toggleButton: {
    name: "",
    enName: "Toggle Button",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ToggleButtonComp",
    compPath: "comps/buttonComp/toggleButtonComp",
    layoutInfo: {
      w: 3,
      h: 6,
    },
  },
  segmentedControl: {
    name: "",
    enName: "Segmented Control",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "SegmentedControlComp",
    compPath: "comps/selectInputComp/segmentedControl",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },

  rating: {
    name: "",
    enName: "Rating",
    description: "",
    categories: ["forms"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "RatingComp",
    compPath: "comps/ratingComp",
    layoutInfo: {
      w: 6,
      h: 6,
    },
  },

  // Project Management

  ganttChart: {
    name: "",
    enName: "ganttChart",
    description: "",
    categories: ["projectmanagement"],
    icon: null,
    keywords: "",
    comp: remoteComp({
      compName: "ganttchart",
      packageName: "lowcoder-comp-gantt-chart",
      source: "npm",
      isRemote: true,
    }),
    compName: "lowcoder-comp-gantt-chart",
    layoutInfo: {
      w: 20,
      h: 60,
    },
  },

  kanban: {
    name: "",
    enName: "Kanban",
    description: "",
    categories: ["projectmanagement"],
    icon: null,
    keywords: "",
    comp: remoteComp({
      compName: "kanban",
      packageName: "lowcoder-comp-kanban",
      source: "npm",
      isRemote: true,
    }),
    compName: "lowcoder-comp-kanban",
    layoutInfo: {
      w: 20,
      h: 60,
    },
  },

  hillchart: {
    name: "",
    enName: "Hillchart",
    description: "",
    categories: ["projectmanagement"],
    icon: null,
    keywords: "",
    comp: remoteComp({
      compName: "hillcharts",
      packageName: "lowcoder-comp-hillcharts",
      source: "npm",
      isRemote: true,
    }),
    compName: "lowcoder-comp-hillcharts",
    layoutInfo: {
      w: 12,
      h: 50,
    },
  },
  bpmnEditor: {
    name: "",
    enName: "BPMN Editor",
    description: "",
    categories: ["projectmanagement", "documents"],
    icon: null,
    keywords: "",
    comp: remoteComp({
      compName: "bpmn",
      packageName: "lowcoder-comp-bpmn-io",
      source: "npm",
      isRemote: true,
    }),
    compName: "lowcoder-comp-bpmn-io",
    layoutInfo: {
      w: 19,
      h: 60,
    },
  },
  progress: {
    name: "",
    enName: "Progress",
    description: "",
    categories: ["dashboards", "projectmanagement"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ProgressComp",
    compPath: "comps/progressComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },
  progressCircle: {
    name: "",
    enName: "Process Circle",
    description: "",
    categories: ["dashboards", "projectmanagement"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ProgressCircleComp",
    compPath: "comps/progressCircleComp",
    layoutInfo: {
      w: 6,
      h: 20,
    },
  },

  // Document handling

  file: {
    name: "",
    enName: "File Upload",
    description: "",
    categories: ["documents"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "FileComp",
    compPath: "comps/fileComp/fileComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },
  fileViewer: {
    name: "",
    enName: "File Viewer",
    description: "",
    categories: ["documents"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "FileViewerComp",
    compPath: "comps/fileViewerComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },

  // Multimedia

  image: {
    name: "",
    enName: "Image",
    description: "",
    categories: ["multimedia"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ImageComp",
    compPath: "comps/imageComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  carousel: {
    name: "",
    enName: "Carousel",
    description: "",
    categories: ["multimedia"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "CarouselComp",
    compPath: "comps/carouselComp",
    withoutLoading: true,
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  audio: {
    name: "",
    enName: "Audio",
    description: "",
    categories: ["multimedia"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "AudioComp",
    compPath: "comps/mediaComp/audioComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },
  video: {
    name: "",
    enName: "Video",
    description: "",
    categories: ["multimedia"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "VideoComp",
    compPath: "comps/mediaComp/videoComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },

  shape: {
    name: "",
    enName: "Shape",
    description: "",
    categories: ["multimedia", "dashboards"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ShapeComp",
    compPath: "comps/shapeComp/shapeComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },

  jsonLottie: {
    name: "",
    enName: "",
    description: "",
    categories: ["multimedia"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "JsonLottieComp",
    compPath: "comps/jsonComp/jsonLottieComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  icon: {
    name: "",
    enName: "icon",
    description: "",
    categories: ["multimedia"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "IconComp",
    compPath: "comps/iconComp",
    layoutInfo: {
      w: 2,
      h: 10,
    },
  },
  imageEditor: {
    name: "",
    enName: "Image Editor",
    comp: remoteComp({ ...builtInRemoteComps, compName: "imageEditor" }),
    description: "",
    categories: ["multimedia"],
    icon: null,
    keywords: "",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },

  // added by Mousheng
  colorPicker: {
    name: "",
    enName: "colorPicker",
    description: "",
    categories: ["multimedia"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ColorPickerComp",
    compPath: "comps/mediaComp/colorPickerComp",
  },

  // item Handling

  qrCode: {
    name: "",
    enName: "QR Code",
    description: "",
    categories: ["itemHandling", "documents"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "QRCodeComp",
    compPath: "comps/qrCodeComp",
    layoutInfo: {
      w: 6,
      h: 32,
    },
  },
  scanner: {
    name: "",
    enName: "Scanner",
    description: "",
    categories: ["itemHandling"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "ScannerComp",
    compPath: "comps/buttonComp/scannerComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },
  signature: {
    name: "",
    enName: "Signature",
    description: "",
    categories: ["itemHandling"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "SignatureComp",
    compPath: "comps/signatureComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  select: {
    name: "",
    enName: "Select",
    description: "",
    categories: ["forms", "itemHandling"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "SelectComp",
    compPath: "comps/selectInputComp/selectComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },
  tour: {
    name: "",
    enName: "Tour",
    description: "",
    categories: ["multimedia", "itemHandling"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "TourComp",
    compPath: "comps/tourComp/tourComp",
    layoutInfo: {
      w: 1,
      h: 1,
    },
  },
  multiSelect: {
    name: "",
    enName: "Multiselect",
    description: "",
    categories: ["forms", "itemHandling"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "MultiSelectComp",
    compPath: "comps/selectInputComp/multiSelectComp",
    layoutInfo: {
      w: 6,
      h: 5,
    },
  },
  tree: {
    name: "",
    enName: "Tree",
    description: "",
    categories: ["layout", "itemHandling", "documents"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "TreeComp",
    compPath: "comps/treeComp/treeComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  treeSelect: {
    name: "",
    enName: "Tree Select",
    description: "",
    categories: ["layout", "itemHandling", "documents"],
    icon: null,
    keywords: "",
    lazyLoad: true,
    compName: "TreeSelectComp",
    compPath: "comps/treeComp/treeSelectComp",
    layoutInfo: {
      w: 12,
      h: 5,
    },
  },
  transfer: {
    name: "",
    enName: "transfer",
    icon: null,
    description: "",
    categories: ["itemHandling", "documents"],
    keywords: "",
    lazyLoad: true,
    compName: "transferComp",
    compPath: "comps/transferComp",
    layoutInfo: {
      w: 12,
      h: 50,
    },
  },
    turnstileCaptcha: {
      name: "",
      enName: "Cloudflare Turnstile",
      description: "",
      categories: ["itemHandling"],
      icon: null,
      keywords: "",
      comp: remoteComp({
         compName: "cloudflareTurnstile",
         packageName: "lowcoder-comp-cf-turnstile",
         source: "npm",
         isRemote: true,
       }),
      compName: "lowcoder-comp-cf-turnstile",
      layoutInfo: {
        w: 8,
        h: 20,
      },
    },

  // Integration

  iframe: {
    name: "",
    enName: "IFrame",
    description: "",
    icon: null,
    categories: ["integration"],
    keywords: "",
    lazyLoad: true,
    compName: "IFrameComp",
    compPath: "comps/iframeComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  custom: {
    name: "",
    enName: "Custom Component",
    description: "",
    icon: null,
    categories: ["integration"],
    keywords: "",
    lazyLoad: true,
    compName: "CustomComp",
    compPath: "comps/customComp/customComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },
  module: {
    name: "",
    enName: "Module",
    icon: null,
    description: "",
    categories: [],
    keywords: "",
    lazyLoad: true,
    compName: "ModuleComp",
    compPath: "comps/moduleComp/moduleComp",
    layoutInfo: {
      w: 12,
      h: 40,
    },
  },

  // mixed

  text: {
    name: "",
    enName: "Text",
    description: "",
    categories: ["dashboards", "layout", "multimedia"],
    icon: null,
    keywords: "",
    compName: "TextComp",
    lazyLoad: true,
    compPath: "comps/textComp",
    layoutInfo: {
      w: 6,
      h: 24,
    },
  },
};

export function loadComps() {
  if (!uiCompMap) return;
  const entries = Object.entries(uiCompMap);
  for (const [compType, manifest] of entries) {
    registerComp(compType as UICompType, manifest);
  }
}
