package org.lowcoder.plugin.googlesheets.queryhandler;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.lang.reflect.Method;
import java.net.ProxySelector;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import org.junit.jupiter.api.AfterEach;
import org.lowcoder.plugin.googlesheets.GoogleSheetsPlugin.GoogleSheetsEngine;
import org.lowcoder.plugin.googlesheets.model.GoogleSheetsQueryExecutionContext;
import org.lowcoder.sdk.contract.RecordingHttpServer;
import org.lowcoder.sdk.contract.RecordingHttpServer.Handler;
import org.lowcoder.sdk.contract.RecordingHttpServer.Request;
import org.lowcoder.sdk.contract.RecordingHttpServer.Response;
import org.lowcoder.sdk.models.QueryExecutionResult;
import org.lowcoder.sdk.query.QueryVisitorContext;
import org.lowcoder.sdk.util.JsonUtils;

import com.google.auth.oauth2.ServiceAccountCredentials;

/**
 * Runs a Google Sheets query the way production does ({@code buildQueryExecutionContext} then {@code executeQuery}) against
 * a local server: the root-URL seam points the Sheets client at it, the service-account credentials get their token
 * endpoint at the same server ({@code /token}, the library signs a JWT with the key generated by
 * {@code ServiceAccountTestKeys} and the server answers with {@value #TOKEN}), and a {@link ForeignHostGuard} fails
 * closed on any other host. The seam and the guard are JVM-wide statics: they are set in {@link #start} and restored
 * in {@code @AfterEach}, and classes using this support must not run in parallel (this module runs them sequentially).
 */
abstract class GoogleSheetsCallSupport {

    static final String SPREADSHEET = "sid";
    static final String TOKEN = "served-token";
    static final String TOKEN_PATH = "/token";
    static final String V4 = "/v4/spreadsheets/";
    private static final String TOKEN_ANSWER = "{\"access_token\":\"" + TOKEN + "\",\"expires_in\":3600,\"token_type\":\"Bearer\"}";
    private static final String JSON = "application/json";

    private final GoogleSheetsEngine engine = new GoogleSheetsEngine();
    private RecordingHttpServer server;
    private ProxySelector previousSelector;
    private ForeignHostGuard guard;

    static Response json(String body) {
        return json(200, body);
    }

    static Response json(int status, String body) {
        return new Response(status, Map.of("Content-Type", List.of(JSON)), body.getBytes(StandardCharsets.UTF_8));
    }

    /** Starts the server with {@code routes} (exact paths, plus the token endpoint), installs the guard and the seam. */
    final void start(Map<String, Handler> routes) {
        Map<String, Handler> all = new java.util.HashMap<>(routes);
        all.put(TOKEN_PATH, request -> json(TOKEN_ANSWER));
        server = RecordingHttpServer.serve(all);
        previousSelector = ProxySelector.getDefault();
        guard = new ForeignHostGuard(Set.of(server.port()));
        ProxySelector.setDefault(guard);
        GoogleSheetsGetPreParameters.setRootUrlForTests(server.baseUrl());
    }

    final void start(String path, Response response) {
        start(Map.of(path, request -> response));
    }

    @AfterEach
    final void stop() {
        GoogleSheetsGetPreParameters.setRootUrlForTests(null);
        if (previousSelector != null) {
            ProxySelector.setDefault(previousSelector);
        }
        if (server != null) {
            server.close();
        }
        if (guard != null) {
            assertEquals(List.of(), guard.foreign(), "a request went to a host or port other than the test's own server");
        }
    }

    final GoogleSheetsQueryExecutionContext context(String commandType, Map<String, Object> command, Map<String, Object> params) {
        GoogleSheetsQueryExecutionContext context = engine.buildQueryExecutionContext(
                engine.resolveConfig(Map.of("serviceAccount", serviceAccountJson())),
                Map.of("commandType", commandType, "command", command), params, new QueryVisitorContext("v", "o", 0, null, null, Set.of()));
        ServiceAccountCredentials real = context.getServiceAccountCredentials();
        context.setServiceAccountCredentials(ServiceAccountCredentials.newBuilder()
                .setClientId(real.getClientId()).setClientEmail(real.getClientEmail()).setPrivateKey(real.getPrivateKey())
                .setPrivateKeyId(real.getPrivateKeyId()).setScopes(real.getScopes())
                .setTokenServerUri(URI.create(server.baseUrl() + TOKEN_PATH)).build());
        return context;
    }

    final QueryExecutionResult run(String commandType, Map<String, Object> command, Map<String, Object> params) {
        return engine.executeQuery(new Object(), context(commandType, command, params)).block();
    }

    final QueryExecutionResult run(String commandType, Map<String, Object> command) {
        return run(commandType, command, Map.of());
    }

    /** All requests the server saw, the token request included. */
    final List<Request> requests() {
        return server.requests();
    }

    /** The requests to the API (everything but the token endpoint). */
    final List<Request> apiRequests() {
        return server.requests().stream().filter(request -> !request.pathAndQuery().startsWith(TOKEN_PATH)).collect(Collectors.toList());
    }

    /** The request body as text; the Google client sends its JSON gzip-compressed. */
    static String bodyText(Request request) {
        if (request.header("Content-Encoding").contains("gzip")) {
            try (java.util.zip.GZIPInputStream in = new java.util.zip.GZIPInputStream(new java.io.ByteArrayInputStream(request.body()))) {
                return new String(in.readAllBytes(), StandardCharsets.UTF_8);
            } catch (java.io.IOException e) {
                throw new IllegalStateException(e);
            }
        }
        return request.bodyText();
    }

    static Map<String, Object> body(Request request) {
        return JsonUtils.fromJsonMap(bodyText(request));
    }

    /** The decoded payload of the JWT assertion a token request carries. */
    static Map<String, Object> assertionPayload(Request tokenRequest) {
        String form = tokenRequest.bodyText();
        String assertion = java.util.Arrays.stream(form.split("&")).filter(part -> part.startsWith("assertion=")).findFirst()
                .orElseThrow().substring("assertion=".length());
        String payload = assertion.split("\\.")[1];
        return JsonUtils.fromJsonMap(new String(Base64.getUrlDecoder().decode(payload), StandardCharsets.UTF_8));
    }

    /** The first message argument of a failed result (the exception text {@code executeQuery} maps). */
    static String failureText(QueryExecutionResult result) {
        return String.valueOf(result.getMessageArgs()[0]);
    }

    private static String serviceAccountJson() {
        try {
            Method json = Class.forName("org.lowcoder.plugin.googlesheets.ServiceAccountTestKeys").getDeclaredMethod("json");
            json.setAccessible(true);
            return (String) json.invoke(null);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException(e);
        }
    }
}
