package org.lowcoder.api.contract.support;

import org.lowcoder.domain.organization.model.Organization;
import org.lowcoder.domain.organization.model.Organization.OrganizationCommonSettings;
import org.lowcoder.domain.organization.model.OrganizationDomain;
import org.lowcoder.domain.organization.model.OrganizationState;
import org.lowcoder.sdk.auth.AbstractAuthConfig;
import org.lowcoder.sdk.auth.EmailAuthConfig;
import org.lowcoder.sdk.auth.Oauth2GenericAuthConfig;
import org.lowcoder.sdk.auth.Oauth2KeycloakAuthConfig;
import org.lowcoder.sdk.auth.Oauth2OryAuthConfig;
import org.lowcoder.sdk.auth.Oauth2SimpleAuthConfig;
import org.lowcoder.sdk.auth.constants.AuthTypeConstants;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * Samples of the organization and auth-config types (docs/API_PAYLOAD_TEST_PLAN.md §3.3, task T2.1), with the
 * conventions of {@link PayloadSamples}. {@code authType} is a real type id in every auth config, because it selects
 * the subtype (§4.4); {@code clientSecret} is {@code @JsonView(Internal)} and carries
 * {@link PayloadSamples#SECRET_MARKER} (§4.5).
 */
public final class OrganizationSamples {

    private OrganizationSamples() {
    }

    /**
     * An organization whose domain holds one config of each of the five {@code AbstractAuthConfig} classes, so that
     * the computed {@code authConfigs} (from the write-only {@code organizationDomain}) carries all of them. The
     * {@code @JsonIgnore}d {@code logoAssetId} and {@code createdAt} are set for the computed {@code logoUrl} and
     * {@code createTime}.
     */
    public static Organization organization() {
        OrganizationDomain domain = new OrganizationDomain();
        domain.setDomain("Organization.organizationDomain.domain");
        domain.setConfigs(new ArrayList<>(List.of(
                emailAuthConfig("Organization.authConfigs[0]"),
                oauth2SimpleAuthConfig("Organization.authConfigs[1]"),
                oauth2GenericAuthConfig("Organization.authConfigs[2]"),
                oauth2KeycloakAuthConfig("Organization.authConfigs[3]"),
                oauth2OryAuthConfig("Organization.authConfigs[4]"))));
        OrganizationCommonSettings settings = new OrganizationCommonSettings();
        settings.put("themeId", "Organization.commonSettings.themeId");
        settings.put("maxRows", 40_100);
        return Organization.builder()
                .id("Organization.id")
                .createdBy("Organization.createdBy")
                .createdAt(ApplicationSamples.instant(100))
                .gid("Organization.gid")
                .slug("Organization.slug")
                .name("Organization.name")
                .isAutoGeneratedOrganization(Boolean.TRUE)
                .contactName("Organization.contactName")
                .contactEmail("Organization.contactEmail")
                .contactPhoneNumber("Organization.contactPhoneNumber")
                .isEmailDisabled(Boolean.TRUE)
                .logoAssetId("Organization.logoAssetId")
                .source("Organization.source")
                .thirdPartyCompanyId("Organization.thirdPartyCompanyId")
                .state(OrganizationState.DELETED)
                .organizationDomain(domain)
                .commonSettings(settings)
                .build();
    }

    public static EmailAuthConfig emailAuthConfig() {
        return emailAuthConfig("EmailAuthConfig");
    }

    static EmailAuthConfig emailAuthConfig(String prefix) {
        return common(EmailAuthConfig.builder(), prefix, AuthTypeConstants.FORM).build();
    }

    public static Oauth2SimpleAuthConfig oauth2SimpleAuthConfig() {
        return oauth2SimpleAuthConfig("Oauth2SimpleAuthConfig");
    }

    static Oauth2SimpleAuthConfig oauth2SimpleAuthConfig(String prefix) {
        return common(Oauth2SimpleAuthConfig.builder(), prefix, AuthTypeConstants.GOOGLE)
                .clientId(prefix + ".clientId")
                .clientSecret(PayloadSamples.SECRET_MARKER + prefix + ".clientSecret")
                .build();
    }

    public static Oauth2GenericAuthConfig oauth2GenericAuthConfig() {
        return oauth2GenericAuthConfig("Oauth2GenericAuthConfig");
    }

    /** Its booleans are opposite to {@code AuthConfigFactoryImpl}'s defaults, as in {@code PayloadSamples#authConfigRequest}. */
    static Oauth2GenericAuthConfig oauth2GenericAuthConfig(String prefix) {
        HashMap<String, String> sourceMappings = new HashMap<>();
        sourceMappings.put("uid", prefix + ".sourceMappings.uid");
        sourceMappings.put("email", prefix + ".sourceMappings.email");
        return common(Oauth2GenericAuthConfig.builder(), prefix, AuthTypeConstants.GENERIC)
                .clientId(prefix + ".clientId")
                .clientSecret(PayloadSamples.SECRET_MARKER + prefix + ".clientSecret")
                .sourceDescription(prefix + ".sourceDescription")
                .sourceIcon(prefix + ".sourceIcon")
                .sourceCategory(prefix + ".sourceCategory")
                .issuerUri(prefix + ".issuerUri")
                .authorizationEndpoint(prefix + ".authorizationEndpoint")
                .tokenEndpoint(prefix + ".tokenEndpoint")
                .userInfoEndpoint(prefix + ".userInfoEndpoint")
                .scope(prefix + ".scope")
                .sourceMappings(sourceMappings)
                .userInfoIntrospection(Boolean.TRUE)
                .userCanSelectAccounts(Boolean.FALSE)
                .postForUserEndpoint(Boolean.TRUE)
                .build();
    }

    public static Oauth2KeycloakAuthConfig oauth2KeycloakAuthConfig() {
        return oauth2KeycloakAuthConfig("Oauth2KeycloakAuthConfig");
    }

    static Oauth2KeycloakAuthConfig oauth2KeycloakAuthConfig(String prefix) {
        return common(Oauth2KeycloakAuthConfig.builder(), prefix, AuthTypeConstants.KEYCLOAK)
                .clientId(prefix + ".clientId")
                .clientSecret(PayloadSamples.SECRET_MARKER + prefix + ".clientSecret")
                .baseUrl(prefix + ".baseUrl")
                .realm(prefix + ".realm")
                .scope(prefix + ".scope")
                .build();
    }

    public static Oauth2OryAuthConfig oauth2OryAuthConfig() {
        return oauth2OryAuthConfig("Oauth2OryAuthConfig");
    }

    static Oauth2OryAuthConfig oauth2OryAuthConfig(String prefix) {
        return common(Oauth2OryAuthConfig.builder(), prefix, AuthTypeConstants.ORY)
                .clientId(prefix + ".clientId")
                .clientSecret(PayloadSamples.SECRET_MARKER + prefix + ".clientSecret")
                .baseUrl(prefix + ".baseUrl")
                .scope(prefix + ".scope")
                .build();
    }

    /** The {@code AbstractAuthConfig} properties; {@code enable} and {@code enableRegister} differ so a swap shows. */
    private static <B extends AbstractAuthConfig.AbstractAuthConfigBuilder<?, ?>> B common(B builder, String prefix, String authType) {
        builder.id(prefix + ".id").source(prefix + ".source").sourceName(prefix + ".sourceName")
                .enable(Boolean.TRUE).enableRegister(Boolean.FALSE).authType(authType);
        return builder;
    }
}
